# download path contains version without the last (fourth) digit
%define libo_version 4.3.7
# Should contain .alphaX / .betaX, if this is pre-release (actually
# pre-RC) version. The pre-release string is part of tarball file names,
# so we need a way to define it easily at one place.
%define libo_prerelease %{nil}
# rhbz#715152 state vendor
%if 0%{?rhel}
%define vendoroption --with-vendor="Red Hat, Inc."
%define libo_use_python3 %{nil}
%define libo_python python
%define libo_python_sitearch %{python_sitearch}
%endif
%if 0%{?fedora}
%define libo_use_python3 1
%define libo_python python3
%define libo_python_sitearch %{python3_sitearch}
%define vendoroption --with-vendor="The Fedora Project"
%endif
# rhbz#465664 jar-repacking breaks help by reordering META-INF/MANIFEST.MF
%define __jar_repack %{nil}
# make it easier to download sources from pre-release site
# http://dev-builds.libreoffice.org/pre-releases/src
# %%define source_url http://dev-builds.libreoffice.org/pre-releases/src
%define source_url http://download.documentfoundation.org/libreoffice/src/%{libo_version}
# URL for external projects' tarballs
%define external_url http://dev-www.libreoffice.org/src/
# limit to fedora, as it breaks building of some bundled projects
%if 0%{?fedora}
# default for f23 onwards
%global _hardened_build 1
%endif

# get english only and no-langpacks for a faster smoketest build
# fedpkg compile/install/local/mockbuild does not handle --without ATM,
# so it is necessary to change this to bcond_with to achieve the same
# effect
%bcond_without langpacks

# remove workdir at the end of %%build, to allow build on space-constrained machines
%ifarch s390 s390x
%bcond_without smallbuild
%else
%bcond_with smallbuild
%endif

# generated by %%langpack definitions
%global langpack_langs %{nil}

%global bundling_options %{nil}

Summary:        Free Software Productivity Suite
Name:           libreoffice
Epoch:          1
Version:        %{libo_version}.2
Release:        2%{?libo_prerelease}%{?dist}
License:        (MPLv1.1 or LGPLv3+) and LGPLv3 and LGPLv2+ and BSD and (MPLv1.1 or GPLv2 or LGPLv2 or Netscape) and Public Domain and ASL 2.0 and Artistic and MPLv2.0 and CC0
Group:          Applications/Productivity
URL:            http://www.libreoffice.org/

Source0:        %{source_url}/libreoffice-%{version}%{?libo_prerelease}.tar.xz
Source1:        %{source_url}/libreoffice-help-%{version}%{?libo_prerelease}.tar.xz
Source2:        %{source_url}/libreoffice-translations-%{version}%{?libo_prerelease}.tar.xz
Source3:        http://dev-www.libreoffice.org/extern/185d60944ea767075d27247c3162b3bc-unowinreg.dll
Source4:        libreoffice-multiliblauncher.sh
Source5:        %{external_url}/a7983f859eafb2677d7ff386a023bc40-xsltml_2.1.2.zip
Source6:        %{external_url}/1f24ab1d39f4a51faf22244c94a6203f-xmlsec1-1.2.14.tar.gz
Source7:        %{external_url}/798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip
Source8:        %{external_url}/35c94d2df8893241173de1d16b6034c0-swingExSrc.zip

%if 0%{?fedora} || 0%{?rhel} >= 7
#Unfortunately later versions of hsqldb changed the file format, so if we use a later version we loose
#backwards compatability.
Source9:        %{external_url}/17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip
%global bundling_options %{?bundling_options} --without-system-hsqldb
%endif

%if 0%{?rhel}
Source10:       %{external_url}/0168229624cfac409e766913506961a8-ucpp-1.3.2.tar.gz
Source11:       %{external_url}/594eb47b4b1210e25438d51825404d5a-glew-1.10.0.zip
Source12:       %{external_url}/bae83fa5dc7f081768daace6e199adc3-glm-0.9.4.6-libreoffice.zip
Source13:       %{external_url}/7681383be6ce489d84c1c74f4e7f9643-liborcus-0.7.0.tar.bz2
%global bundling_options %{?bundling_options} --without-system-ucpp --without-system-glew --without-system-glm --without-system-orcus
%if 0%{?rhel} < 7
Source14:       %{external_url}/cb4207cb913c7a5a8bfa5b91234618ee-mdds_0.11.2.tar.bz2
Source15:       %{external_url}/46e92b68e31e858512b680b3b61dc4c1-mythes-1.2.3.tar.gz
Source16:       %{external_url}/32f8e1417a64d3c6f2c727f9053f55ea-redland-1.0.16.tar.gz
Source17:       %{external_url}/4ceb9316488b0ea01acf011023cf7fff-raptor2-2.0.9.tar.gz
Source18:       %{external_url}/b12c5f9cfdb6b04efce5a4a186b8416b-rasqal-0.9.30.tar.gz
Source19:       %{external_url}/ae330b9493bd4503ac390106ff6060d7-libexttextcat-3.4.3.tar.bz2
Source20:       %{external_url}/48d647fbd8ef8889e5a7f422c1bfda94-clucene-core-2.3.3.4.tar.gz
Source21:       %{external_url}/lcms2-2.6.tar.gz
Source22:       %{external_url}/36271d3fa0d9dec1632029b6d7aac925-liblangtag-0.5.1.tar.bz2
Source23:       %{external_url}/d6eef4b4cacb2183f2bf265a5a03a354-boost_1_55_0.tar.bz2
Source24:       %{external_url}/harfbuzz-0.9.23.tar.bz2
Source25:       %{external_url}/22f8a85daf4a012180322e1f52a7563b-libcmis-0.4.1.tar.gz
Source26:       %{external_url}/language-subtag-registry-2014-12-03.tar.bz2
%global bundling_options %{?bundling_options} --without-system-mdds --without-system-mythes --without-system-redland --without-system-libexttextcat --without-system-clucene --without-system-lcms2 --without-system-liblangtag --without-system-boost --without-system-harfbuzz --without-system-libcmis
%endif
Source27:       %{external_url}/libcdr-0.1.0.tar.bz2
Source28:       %{external_url}/libwpg-0.3.0.tar.bz2
Source29:       %{external_url}/libwpd-0.10.0.tar.bz2
Source30:       %{external_url}/libwps-0.3.0.tar.bz2
Source31:       %{external_url}/libvisio-0.1.0.tar.bz2
Source32:       %{external_url}/libmspub-0.1.1.tar.bz2
Source33:       %{external_url}/libodfgen-0.1.1.tar.bz2
Source34:       %{external_url}/libmwaw-0.3.1.tar.bz2
Source35:       %{external_url}/libetonyek-0.1.1.tar.bz2
Source36:       %{external_url}/libfreehand-0.1.0.tar.bz2
Source37:       %{external_url}/libabw-0.1.0.tar.bz2
Source38:       %{external_url}/librevenge-0.0.1.tar.bz2
%global bundling_options %{?bundling_options} --without-system-libcdr --without-system-libwpg --without-system-libwpd --without-system-libwps --without-system-libvisio --without-system-libmspub --without-system-libodfgen --without-system-libmwaw --without-system-libetonyek --without-system-libfreehand --without-system-libabw --without-system-librevenge
%endif

%if 0%{?fedora}
Source39:       %{external_url}/4b87018f7fff1d054939d19920b751a0-collada2gltf-master-cb1d97788a.tar.bz2
%endif

# build tools
BuildRequires: autoconf
BuildRequires: automake
BuildRequires: bc
BuildRequires: binutils
BuildRequires: bison
%if 0%{?rhel} && 0%{?rhel} < 7
BuildRequires: chrpath
%endif
BuildRequires: desktop-file-utils
BuildRequires: doxygen
BuildRequires: findutils
BuildRequires: flex
BuildRequires: gcc-c++
BuildRequires: gdb
BuildRequires: git
BuildRequires: gperf
BuildRequires: icu
BuildRequires: make
BuildRequires: perl(Archive::Zip)
BuildRequires: perl(Digest::MD5)
%if 0%{?fedora}
BuildRequires: ucpp
%endif
BuildRequires: zip

# libs / headers - common
BuildRequires: cups-devel
BuildRequires: expat-devel
BuildRequires: fontpackages-devel
BuildRequires: hyphen-devel
BuildRequires: libicu-devel
BuildRequires: lpsolve-devel
BuildRequires: openldap-devel
BuildRequires: pam-devel
BuildRequires: pkgconfig(cppunit)
BuildRequires: pkgconfig(dbus-glib-1)
BuildRequires: pkgconfig(evolution-data-server-1.2)
BuildRequires: pkgconfig(freetype2)
BuildRequires: pkgconfig(gconf-2.0)
BuildRequires: pkgconfig(glu)
BuildRequires: pkgconfig(gtk+-2.0)
BuildRequires: pkgconfig(hunspell)
BuildRequires: pkgconfig(ice)
BuildRequires: pkgconfig(libcurl)
BuildRequires: pkgconfig(libidn)
BuildRequires: pkgconfig(libxml-2.0)
BuildRequires: pkgconfig(libxslt)
BuildRequires: pkgconfig(neon)
BuildRequires: pkgconfig(nss)
BuildRequires: pkgconfig(poppler)
BuildRequires: pkgconfig(redland)
BuildRequires: pkgconfig(sane-backends)
BuildRequires: pkgconfig(xext)
BuildRequires: pkgconfig(xinerama)
BuildRequires: pkgconfig(xt)
BuildRequires: pkgconfig(zlib)
BuildRequires: unixODBC-devel
BuildRequires: vigra-devel

# libs / headers - conditional
%if 0%{?fedora}
BuildRequires: firebird-devel
BuildRequires: firebird-libfbembed
BuildRequires: glm-devel
BuildRequires: kdelibs4-devel
BuildRequires: openCOLLADA-devel
BuildRequires: pkgconfig(glew) >= 1.10.0
BuildRequires: pkgconfig(libabw-0.1)
BuildRequires: pkgconfig(libcdr-0.1)
BuildRequires: pkgconfig(libe-book-0.1)
BuildRequires: pkgconfig(libeot)
BuildRequires: pkgconfig(libetonyek-0.1)
BuildRequires: pkgconfig(libfreehand-0.1)
BuildRequires: pkgconfig(libgltf-0.0)
BuildRequires: pkgconfig(libmspub-0.1)
BuildRequires: pkgconfig(libmwaw-0.3)
BuildRequires: pkgconfig(libodfgen-0.1)
BuildRequires: pkgconfig(liborcus-0.8)
BuildRequires: pkgconfig(librevenge-0.0)
BuildRequires: pkgconfig(libvisio-0.1)
BuildRequires: pkgconfig(libwpd-0.10)
BuildRequires: pkgconfig(libwpg-0.3)
BuildRequires: pkgconfig(libwps-0.3)
%endif

%if 0%{?fedora} || 0%{?rhel} >= 7
BuildRequires: boost-devel
BuildRequires: pkgconfig(graphite2)
BuildRequires: pkgconfig(harfbuzz)
BuildRequires: pkgconfig(lcms2)
BuildRequires: pkgconfig(libclucene-core)
BuildRequires: pkgconfig(libexttextcat)
BuildRequires: pkgconfig(libcmis-0.4)
BuildRequires: pkgconfig(liblangtag)
BuildRequires: pkgconfig(mdds)
BuildRequires: pkgconfig(mythes)
BuildRequires: pkgconfig(poppler-cpp)
BuildRequires: postgresql-devel
%endif

# libs / headers - special cases
%if 0%{?rhel} && 0%{?rhel} < 7
BuildRequires: gstreamer-devel
BuildRequires: gstreamer-plugins-base-devel
%else
BuildRequires: pkgconfig(gstreamer-1.0)
BuildRequires: pkgconfig(gstreamer-plugins-base-1.0)
%endif

%if 0%{?fedora} || 0%{?rhel} >= 7
BuildRequires: libjpeg-turbo-devel
%else
BuildRequires: libjpeg-devel
%endif

%if 0%{?fedora} || 0%{?rhel} >= 7
BuildRequires: pkgconfig(bluez)
%else
%ifnarch s390 s390x
BuildRequires: pkgconfig(bluez)
%endif
%endif

BuildRequires: %{libo_python}-devel

# java stuff
BuildRequires: ant
%if 0%{?rhel} && 0%{?rhel} < 7
BuildRequires: jakarta-commons-codec
BuildRequires: jakarta-commons-lang
%else
BuildRequires: apache-commons-codec
BuildRequires: apache-commons-lang
%endif
BuildRequires: bsh
%if 0%{?rhel} && 0%{?rhel} < 7
BuildRequires: hsqldb
%endif
BuildRequires: java-devel
BuildRequires: jakarta-commons-httpclient
%if 0%{?fedora} || 0%{?rhel} >= 7
BuildRequires: junit
%endif
BuildRequires: pentaho-reporting-flow-engine

# fonts needed for unit tests
BuildRequires: liberation-mono-fonts
BuildRequires: liberation-sans-fonts
BuildRequires: liberation-serif-fonts

Requires: %{name}-writer = %{epoch}:%{version}-%{release}
Requires: %{name}-calc = %{epoch}:%{version}-%{release}
Requires: %{name}-impress = %{epoch}:%{version}-%{release}
Requires: %{name}-draw = %{epoch}:%{version}-%{release}
Requires: %{name}-math = %{epoch}:%{version}-%{release}
Requires: %{name}-base = %{epoch}:%{version}-%{release}
Requires: %{name}-emailmerge = %{epoch}:%{version}-%{release}

# not upstreamed
Patch0:  openoffice.org-2.4.0.ooo86080.unopkg.bodge.patch
# not upstreamed
Patch1:  openoffice.org-3.1.0.oooXXXXX.solenv.allowmissing.patch
# not upstreamed
Patch2:  libreoffice-installfix.patch
%if 0%{?rhel}
# not upstreamed
Patch3: 0001-disable-failing-test-on-rhel.patch
%if 0%{?rhel} < 7
# not upstreamed
Patch4: libreoffice-rhel6gcj.patch
# not upstreamed
Patch5: libreoffice-rhel6poppler.patch
# not upstreamed
Patch6: libreoffice-rhel6langs.patch
# not upstreamed
Patch7: libreoffice-rhel6glib.patch
# not upstreamed
Patch8: 0001-disable-failing-test-on-rhel-6.patch
%endif
# not upstreamed
# TODO: fails on ppc; investigate
Patch9: 0001-disable-swui-test-on-RHEL-7.patch
# not upstreamed
Patch10: 0001-disable-libe-book-support.patch
%else
Patch11: 0001-disable-failing-while-libmwaw-fix-pending.patch
%endif
# not upstreamed
Patch12: 0001-Resolves-rhbz-1035092-no-shortcut-key-for-Italian-To.patch
# not upstreamed
Patch13: 0001-disable-firebird-unit-test.patch
# not upstreamed
Patch14: 0001-never-run-autogen.sh.patch
# not upstreamed
Patch15: 0001-add-X-TryExec-entries-to-desktop-files.patch
# not upstreamed
Patch16: 0001-disable-PSD-import-test-which-deadlocks-on-ARM.patch
Patch17: 0001-rhbz-1111216-allow-to-export-an-empty-sheet-to-PDF.patch
Patch18: 0001-avoid-problems-detecting-HTML-files-with-.xls-ext.patch
Patch19: 0001-scrolling-very-slow-in-calc.patch
Patch20: 0001-Related-rhbz-1117853-nStartPara-of-EE_PARA_NOT_FOUND.patch
Patch21: 0001-Resolves-fdo-81487-pasting-into-outline-view-crashes.patch
Patch22: 0001-Related-rhbz-1130264-plausible-fix-for-reported-cras.patch
Patch23: 0001-if-_CALL_ELF-if-defined-_CALL_ELF-_CALL_ELF-2.patch
Patch24: 0002-Linux-AArch64-port.patch
Patch25: 0001-fix-KDE4-detection-on-aarch64.patch
Patch26: 0001-drop-useless-test-for-ant-apache-regexp.patch
Patch27: 0001-No-fstack-protect-strong-for-gcc3_linux_aarch64-cpp2.patch
Patch28: 0001-fdo-82496-Change-picture-option-by-rightclicking.patch
Patch29: 0001-create-a-master-document-template-type.patch
Patch30: 0001-Resolves-fdo-80911-don-t-swap-notes-page-width-heigh.patch
Patch31: 0001-default-n-up-printing-of-notes-to-sensible-2-x-1-not.patch
Patch32: 0001-n-up-printing-done-by-vcl-brochures-by-draw-impress.patch
Patch33: 0001-Resolves-fdo-68967-looping-layout.patch
Patch34: 0001-Remove-smb-from-X-KDE-Protocols-lines.patch
Patch35: 0001-libgcrypt-and-gnutls-are-only-used-by-our-internal-e.patch
Patch36: 0001-allow-to-build-with-system-opencollada.patch
Patch37: 0001-Resolves-fdo-37559-revert-adding-extra-dummy-polygon.patch
Patch38: 0001-implement-toggling-off-removeable-master-elements-wi.patch
Patch39: 0001-Resolves-fdo-78151-change-style-on-toggling-bullets-.patch
Patch40: 0001-Resolves-rhbz-1161238-sync-PRESOBJ_OUTLINE-para-dept.patch
Patch41: 0001-strip-off-hard-coded-numbering-from-outliner-preview.patch
Patch42: 0001-have-a-stab-at-improving-impossible-question.patch
Patch43: 0001-just-use-ANSI-C-declarations.patch
Patch44: 0001-Related-fdo-78151-only-make-outline-title-and-subtit.patch
Patch45: 0001-ooo-93212-avoid-slicing-during-construction-of-SdrPa.patch
Patch46: 0001-don-t-copy-stylesheet-s-HelpID-if-this-s-a-rename.patch
Patch47: 0001-fdo-37682-paint-the-right-area.patch
Patch48: 0001-Related-fdo-87242-init-VirtualDevice-with-size-of-su.patch
Patch49: 0001-fdo-36772-Move-the-scrollbar-and-sheet-tabs-in-a-sep.patch
Patch50: 0001-radio-check-top-center-bottom-alignment-for-table-ce.patch
Patch51: 0001-allow-comparing-documents-which-only-differ-by-frame.patch
Patch52: 0001-Use-the-same-advanced-Ellipse-and-Rectangle-shapes-i.patch
Patch53: 0001-if-we-change-the-keys-we-have-to-resort-based-on-the.patch
Patch54: 0001-don-t-strip-font-names-of-apparent-script-suffixes-a.patch
Patch55: 0001-During-DocumentRedlineManager-SetRedlineMode-the-arr.patch
Patch56: 0001-Resolves-rhbz-1193971-clear-hard-coded-char-props-in.patch
Patch57: 0001-add-accel.-to-switch-monitors-to-pres.-console.patch
Patch58: 0001-build-libetonyek-with-no-strict-aliasing.patch
Patch59: 0002-propagate-user-set-CFLAGS-to-build.patch
Patch60: 0001-fdo-69036-do-not-try-to-create-a-sfxApplication-when.patch
Patch61: 0001-Resolves-rhbz-1204244-group-sdb-windows-together-as-.patch
Patch62: 0001-Resolves-tdf-90256-repair-invalid-docking-positions.patch
Patch63: 0001-negative-after-text-indents-ignored-by-msword-for-ap.patch
Patch64: 0001-Resolves-tdf-73211-gtk-checkboxes-need-erase-afer-to.patch
Patch65: 0001-rhbz-1198848-sw-delete-all-table-redlines-to-fix-DOC.patch
Patch66: 0001-Resolves-rhbz-1215060-get-LibreOffice-to-load-specif.patch
Patch67: 0001-tdf-87400-sw-fix-SwIndexReg-assertion-in-AutoCorrect.patch
Patch68: 0002-sw-fix-crash-on-SwUndoDelete-after-select-all-with-t.patch
Patch69: 0003-rhbz-1205072-sw-resource-mangement-SNAFU-caused-by-S.patch
Patch70: 0004-sw-fix-SwAccessibleParagraph-crash-on-delete.patch
Patch71: 0001-DOCX-import-fix-handling-of-dropdown-SDT-around-cell.patch
Patch72: 0001-rhbz-1213173-connectivity-Calc-driver-prevent-docume.patch
Patch73: 0001-Resolves-tdf-90757-ensure-start-row-end-row-order-ma.patch
Patch74: 0001-Resolves-tdf-91078-check-also-DBData-modified-not-on.patch
Patch75: 0001-misspell-some-words-copy-and-paste-slide-to-gimp.patch
Patch76: 0001-java-dir-for-powepc64-and-powepc64le-can-differ.patch
Patch77: 0002-java-dir-for-powepc64-and-powepc64le-can-differ.patch
Patch78: 0001-rulers-Make-the-numbers-a-bit-smaller-and-always-wit.patch
Patch79: 0001-Resolves-tdf-91420-Jan1-2015-is-a-valid-date.patch
Patch80: 0001-tdf-91425-CRASH-Calc-Insert-Columns-Left.patch
Patch81: 0001-tdf-78854-do-not-crash-when-undoing-layout-change.patch
Patch82: 0001-do-not-access-token-data-after-token-has-been-destro.patch
Patch83: 0001-Resolves-tdf-86305-clone-upper-left-of-matrix-result.patch
Patch84: 0001-Resolves-tdf-83365-push-proper-references-in-INDIREC.patch
Patch85: 0001-rhbz-1233420-handle-inexistent-cond.-format.patch
Patch86: 0001-a-singleton-must-be-fully-parsed-to-be-valid-tdf-444.patch
Patch87: 0001-tdf-44419-in-second-reference-part-stop-number-parsi.patch
Patch88: 0001-Resolves-tdf-92275-impress-grinds-to-a-halt-constant.patch
Patch89: 0001-Resolves-tdf-31577-volatile-lookup-ranges-must-not-b.patch
Patch90: 0001-always-justify-a-referenced-range-in-order-tdf-92468.patch
Patch91: 0001-Resolves-tdf-84762-collect-all-recalc-always-cells-b.patch
Patch94: 0001-Resolves-tdf-92767-use-ISO-8601-for-internal-date-st.patch
Patch95: 0001-check-annotation-caption-pointers-blind-fix-for-rhbz.patch
Patch96: 0001-Resolves-tdf-86024-do-not-attempt-to-shorten-numeric.patch
Patch97: 0001-fix-langtag-test-with-liblangtag-0.5.7.patch
Patch98: 0001-support-en-GB-oxendict-additionally-to-now-deprecate.patch
Patch99: 0001-Resolves-rhbz-1255811-implement-Edit-modify-handler.patch
Patch100: 0001-Resolves-rhbz-1256843-no-obvious-means-to-close-temp.patch
Patch101: 0001-Related-rhbz-1255200-apparent-missing-stylesheet.patch
Patch102: 0001-Resolves-tdf-92995-do-not-delete-caption-objects-tha.patch
Patch103: 0001-Resolves-tdf-85979-TextToColumns-is-overwriting-so-s.patch
Patch104: 0001-Resolves-rhbz-1264585-check-data-pilot-field-name-av.patch
Patch105: 0001-fix-IterateMatrix-for-ifPRODUCT-and-ifSUMSQ.patch
Patch106: 0001-use-exponential-E-format-for-General-when-appropriat.patch
Patch107: 0001-tdf-94173-Calc-doesn-t-save-your-own-created-autofor.patch
Patch108: 0001-xmloff-fix-ODF-import-of-gradient-draw-angle-attribu.patch
Patch109: 0002-tdf-94804-prefix-to-save-cross-reference-bookmark-fi.patch
Patch110: 0001-LinkUpdateMode-is-a-global-setting.patch
Patch111: 0002-coverity-1266485-Untrusted-value-as-argument.patch
Patch112: 0003-ww8-make-sure-we-don-t-wrap-around.patch
Patch113: 0004-convert-pStatus-to-vector-and-use-at-to-check-offset.patch

%define instdir %{_libdir}
%define baseinstdir %{instdir}/libreoffice
%define ureinstdir %{baseinstdir}/ure
%define sdkinstdir %{baseinstdir}/sdk
%define fontname opensymbol

# rhbz#1085420 make sure we do not provide bundled libraries
%if 0%{?rhel}
%global libo_bundled_libs_common GLEW\\|mwaw-0.3\\|odfgen-0.1\\|revenge-0.0\\|wps-0.3
%if 0%{?rhel} < 7
# redland libs are already suffixed -> no need to filter them too
%global libo_bundled_libs_filter /^lib\\(clucene\\|lcms2\\|%libo_bundled_libs_common\\)\\.so.*$/d
%filter_from_provides %{libo_bundled_libs_filter}
%filter_from_requires %{libo_bundled_libs_filter}
%filter_setup
%else
%global libo_bundled_libs_filter ^lib\\(%libo_bundled_libs_common\\)\\.so.*$
%global __provides_exclude %{libo_bundled_libs_filter}
%global __requires_exclude %{libo_bundled_libs_filter}
%endif
%endif

%description
LibreOffice is an Open Source, community-developed, office productivity suite.
It includes the key desktop applications, such as a word processor,
spreadsheet, presentation manager, formula editor and drawing program, with a
user interface and feature set similar to other office suites.  Sophisticated
and flexible, LibreOffice also works transparently with a variety of file
formats, including Microsoft Office File Formats.

%package filters
Summary: All import / export filters
Group: Applications/Productivity
Requires: %{name}-calc = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-draw = %{epoch}:%{version}-%{release}
Requires: %{name}-graphicfilter = %{epoch}:%{version}-%{release}
Requires: %{name}-impress = %{epoch}:%{version}-%{release}
Requires: %{name}-math = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-writer = %{epoch}:%{version}-%{release}
Requires: %{name}-xsltfilter = %{epoch}:%{version}-%{release}

%description filters
Metapackage to pull in all subpackages that contain import or export
filters.

%package core
Summary: Core modules for LibreOffice
Group: Applications/Productivity
Requires: %{name}-%{fontname}-fonts = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: liberation-sans-fonts >= 1.0, liberation-serif-fonts >= 1.0, liberation-mono-fonts >= 1.0
Requires: dejavu-sans-fonts, dejavu-serif-fonts, dejavu-sans-mono-fonts
Requires: google-crosextra-caladea-fonts, google-crosextra-carlito-fonts
Requires: hyphen-en, hyphen >= 2.4, autocorr-en
%if 0%{?rhel} && 0%{?rhel} < 7
Requires: hunspell-en
%else
# rhbz#949106 libreoffice-core drags in both openjdk 1.7.0 and 1.8.0
Requires: java-headless >= 1:1.6
Requires: hunspell-en-US
%endif
Requires(pre):    gtk2 >= 2.9.4
Requires(post):   gtk2 >= 2.9.4
Requires(preun):  gtk2 >= 2.9.4
Requires(postun): gtk2 >= 2.9.4
Obsoletes: libreoffice-appdata < 1:4.3.3.0
Obsoletes: libreoffice-binfilter < 1:4.0.0.0
Obsoletes: libreoffice-javafilter < 1:4.1.0.0
Obsoletes: openoffice.org-core < 1:3.3.1
Obsoletes: openoffice.org-brand < 1:3.3.1, broffice.org-brand < 1:3.3.1
Obsoletes: openoffice.org-javafilter < 1:3.3.1
Obsoletes: openoffice.org-langpack-ms < 1:3.3.1, libreoffice-langpack-ms < 1:3.3.99.1
Obsoletes: openoffice.org-langpack-ur < 1:3.3.1, libreoffice-langpack-ur < 1:3.3.99.1
Obsoletes: openoffice.org-testtools < 1:3.3.1
Obsoletes: libreoffice-testtools < 1:3.4.99.1
Obsoletes: autocorr-eu < 1:4.0.1.2
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-core = 1:3.3.0
Provides: openoffice.org-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-brand = 1:3.3.0, broffice.org-brand = 1:3.3.0
Provides: openoffice.org-brand%{?_isa} = 1:3.3.0, broffice.org-brand%{?_isa} = 1:3.3.0
%endif

%description core
The shared core libraries and support files for LibreOffice.

%package pyuno
Summary: Python support for LibreOffice
Group: Development/Libraries
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{libo_python}
Obsoletes: openoffice.org-pyuno < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-pyuno = 1:3.3.0
Provides: openoffice.org-pyuno%{?_isa} = 1:3.3.0
%endif

%description pyuno
Python bindings for the LibreOffice UNO component model. Allows scripts both
external to LibreOffice and within the internal LibreOffice scripting framework
to be written in python.

%package base
Summary: Database front-end for LibreOffice
Group: Applications/Productivity
Requires: pentaho-reporting-flow-engine
Requires: postgresql-jdbc
%if 0%{?rhel} && 0%{?rhel} < 7
Requires:  hsqldb
%endif
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-calc = %{epoch}:%{version}-%{release}
Obsoletes: %{name}-report-builder < 1:4.1.0.0
Obsoletes: openoffice.org-base-core < 1:3.3.1
Obsoletes: openoffice.org-base < 1:3.3.1, broffice.org-base < 1:3.3.1
Obsoletes: openoffice.org-report-builder < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-base-core = 1:3.3.0
Provides: openoffice.org-base-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-base = 1:3.3.0, broffice.org-base = 1:3.3.0
Provides: openoffice.org-base%{?_isa} = 1:3.3.0, broffice.org-base%{?_isa} = 1:3.3.0
Provides: openoffice.org-report-builder = 1:3.3.0
Provides: openoffice.org-report-builder%{?_isa} = 1:3.3.0
%endif

%description base
GUI database front-end for LibreOffice. Allows creation and management of 
databases through a GUI.

%package bsh
Summary: BeanShell support for LibreOffice
Group: Development/Libraries
Requires: bsh
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-bsh < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-bsh = 1:3.3.0
Provides: openoffice.org-bsh%{?_isa} = 1:3.3.0
%endif

%description bsh
Support BeanShell scripts in LibreOffice.

%package officebean
Summary: JavaBean for LibreOffice Components
Group: Development/Libraries
Requires: %{name}-core = %{epoch}:%{version}-%{release}

%description officebean
Allows embedding of LibreOffice documents within the Java environment. It
provides a Java AWT window into which the backend LibreOffice process draws
its visual representation

%package rhino
Summary: JavaScript support for LibreOffice
Group: Development/Libraries
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-rhino < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-rhino = 1:3.3.0
Provides: openoffice.org-rhino%{?_isa} = 1:3.3.0
%endif

%description rhino
Support JavaScript scripts in LibreOffice.

%package wiki-publisher
Summary: Create Wiki articles on MediaWiki servers with LibreOffice
Group: Applications/Productivity
%if 0%{?rhel} && 0%{?rhel} < 7
Requires: jakarta-commons-codec, jakarta-commons-httpclient
Requires: jakarta-commons-lang, jakarta-commons-logging
%else
Requires: apache-commons-codec, jakarta-commons-httpclient
Requires: apache-commons-lang, apache-commons-logging
%endif
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-writer = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-wiki-publisher < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-wiki-publisher = 1:3.3.0
Provides: openoffice.org-wiki-publisher%{?_isa} = 1:3.3.0
%endif

%description wiki-publisher
The Wiki Publisher enables you to create Wiki articles on MediaWiki servers
without having to know the syntax of the MediaWiki markup language. Publish
your new and existing documents transparently with writer to a wiki page.

%package nlpsolver
Summary: Non-linear solver engine for LibreOffice Calc
Group: Applications/Productivity
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-calc = %{epoch}:%{version}-%{release}

%description nlpsolver
A non-linear solver engine for Calc as an alternative to the default linear
programming model when more complex, nonlinear programming is required.

%package ogltrans
Summary: 3D OpenGL slide transitions for LibreOffice
Group: Applications/Productivity
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-impress = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-ogltrans < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-ogltrans = 1:3.3.0
Provides: openoffice.org-ogltrans%{?_isa} = 1:3.3.0
%endif

%description ogltrans
OpenGL Transitions enable 3D slide transitions to be used in LibreOffice.
Requires good quality 3D support for your graphics card for best experience.

%package pdfimport
Summary: PDF Importer for LibreOffice Draw
Group: Applications/Productivity
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-draw = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-pdfimport < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-pdfimport = 1:3.3.0
Provides: openoffice.org-pdfimport%{?_isa} = 1:3.3.0
%endif

%description pdfimport
The PDF Importer imports PDF into drawing documents to preserve layout
and enable basic editing of PDF documents.

%package %{fontname}-fonts
Summary: LibreOffice dingbats font
Group: User Interface/X
Requires: fontpackages-filesystem
Obsoletes: openoffice.org-fonts < 1:3.3.1
Obsoletes: openoffice.org-opensymbol-fonts < 1:3.3.1
BuildArch: noarch
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-fonts = 1:3.3.0
Provides: openoffice.org-opensymbol-fonts = 1:3.3.0
%endif

%description %{fontname}-fonts
A dingbats font, OpenSymbol, suitable for use by LibreOffice for bullets and
mathematical symbols. 

%package writer
Summary: LibreOffice Word Processor Application
Group: Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-writer-core < 1:3.3.1
Obsoletes: openoffice.org-writer < 1:3.3.1, broffice.org-writer < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-writer-core = 1:3.3.0
Provides: openoffice.org-writer-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-writer = 1:3.3.0, broffice.org-writer = 1:3.3.0
Provides: openoffice.org-writer%{?_isa} = 1:3.3.0, broffice.org-writer%{?_isa} = 1:3.3.0
%endif

%description writer
The LibreOffice Word Processor application.

%package emailmerge
Summary: Email mail-merge component for LibreOffice 
Group: Applications/Productivity
Requires: %{name}-writer = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-emailmerge < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-emailmerge = 1:3.3.0
Provides: openoffice.org-emailmerge%{?_isa} = 1:3.3.0
%endif

%description emailmerge
Enables the LibreOffice writer module to mail-merge to email.

%package calc
Summary: LibreOffice Spreadsheet Application
Group: Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-calc-core < 1:3.3.1
Obsoletes: openoffice.org-calc < 1:3.3.1, broffice.org-calc < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-calc-core = 1:3.3.0
Provides: openoffice.org-calc-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-calc = 1:3.3.0, broffice.org-calc = 1:3.3.0
Provides: openoffice.org-calc%{?_isa} = 1:3.3.0, broffice.org-calc%{?_isa} = 1:3.3.0
%endif

%description calc
The LibreOffice Spreadsheet application.

%package draw
Summary: LibreOffice Drawing Application
Group: Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-pdfimport = %{epoch}:%{version}-%{release}
Requires: %{name}-graphicfilter = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-draw-core < 1:3.3.1
Obsoletes: openoffice.org-draw < 1:3.3.1, broffice.org-draw < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-draw-core = 1:3.3.0
Provides: openoffice.org-draw-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-draw = 1:3.3.0, broffice.org-draw = 1:3.3.0
Provides: openoffice.org-draw%{?_isa} = 1:3.3.0, broffice.org-draw%{?_isa} = 1:3.3.0
%endif

%description draw
The LibreOffice Drawing Application.

%package impress
Summary: LibreOffice Presentation Application
Group: Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Obsoletes: %{name}-presentation-minimizer < 2:4.2.0.0-1.alpha1
Obsoletes: %{name}-presenter-screen < 2:4.0.0.0-1.beta1
Obsoletes: openoffice.org-impress-core < 1:3.3.1
Obsoletes: openoffice.org-impress < 1:3.3.1, broffice.org-impress < 1:3.3.1
Obsoletes: openoffice.org-presentation-minimizer < 1:3.3.1
Obsoletes: openoffice.org-presenter-screen < 1:3.3.1
Provides: %{name}-presentation-minimizer%{?_isa} = %{epoch}:%{version}-%{release}
Provides: %{name}-presenter-screen%{?_isa} = %{epoch}:%{version}-%{release}
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-impress-core = 1:3.3.0
Provides: openoffice.org-impress-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-impress = 1:3.3.0, broffice.org-impress = 1:3.3.0
Provides: openoffice.org-impress%{?_isa} = 1:3.3.0, broffice.org-impress%{?_isa} = 1:3.3.0
Provides: openoffice.org-presentation-minimizer = 1:3.3.0
Provides: openoffice.org-presentation-minimizer%{?_isa} = 1:3.3.0
Provides: openoffice.org-presenter-screen = 1:3.3.0
Provides: openoffice.org-presenter-screen%{?_isa} = 1:3.3.0
%endif

%description impress
The LibreOffice Presentation Application.

%package math
Summary: LibreOffice Equation Editor Application
Group: Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-math-core < 1:3.3.1
Obsoletes: openoffice.org-math < 1:3.3.1, broffice.org-math < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-math-core = 1:3.3.0
Provides: openoffice.org-math-core%{?_isa} = 1:3.3.0
Provides: openoffice.org-math = 1:3.3.0, broffice.org-math = 1:3.3.0
Provides: openoffice.org-math%{?_isa} = 1:3.3.0, broffice.org-math%{?_isa} = 1:3.3.0
%endif

%description math 
The LibreOffice Equation Editor Application.

%package graphicfilter
Summary: LibreOffice Extra Graphic filters
Group: Applications/Productivity
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-graphicfilter < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-graphicfilter = 1:3.3.0
Provides: openoffice.org-graphicfilter%{?_isa} = 1:3.3.0
%endif

%description graphicfilter
The graphicfilter module for LibreOffice provides graphic filters, e.g. svg and
flash filters.

%package xsltfilter
Summary: Optional xsltfilter module for LibreOffice
Group: Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-xsltfilter < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-xsltfilter = 1:3.3.0
Provides: openoffice.org-xsltfilter%{?_isa} = 1:3.3.0
%endif

%description xsltfilter
The xsltfilter module for LibreOffice, provides additional docbook and
xhtml export transforms. Install this to enable docbook export.

%if 0%{?fedora} || 0%{?rhel} >= 7
%package postgresql
Summary: PostgreSQL connector for LibreOffice
Group: Applications/Productivity
Requires: %{name}-base = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: postgresql-libs

%description postgresql
A PostgreSQL connector for the database front-end for LibreOffice. Allows
creation and management of PostgreSQL databases through a GUI.
%endif

%package ure
Summary: UNO Runtime Environment
Group: Development/Libraries
#rhbz#1164551 we want to ensure that a libjvm.so of this arch is available
%if 0%{?__isa_bits} == 64
%global mark64 ()(64bit)
%endif
Requires: unzip, libjvm.so%{?mark64}
Obsoletes: openoffice.org-ure < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-ure = 1:3.3.0
Provides: openoffice.org-ure%{?_isa} = 1:3.3.0
%endif

%description ure
UNO is the component model of LibreOffice. UNO offers interoperability between
programming languages, other components models and hardware architectures,
either in process or over process boundaries, in the Intranet as well as in the
Internet. UNO components may be implemented in and accessed from any
programming language for which a UNO implementation (AKA language binding) and
an appropriate bridge or adapter exists

%package sdk
Summary: Software Development Kit for LibreOffice
Group: Development/Libraries
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: unzip, java-devel
Obsoletes: openoffice.org-sdk < 1:3.3.1, openoffice.org-devel < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-sdk = 1:3.3.0, openoffice.org-devel = 1:3.3.0
Provides: openoffice.org-sdk%{?_isa} = 1:3.3.0, openoffice.org-devel%{?_isa} = 1:3.3.0
%endif

%description sdk
The LibreOffice SDK is an add-on for the LibreOffice office suite. It provides
the necessary tools for programming using the LibreOffice APIs and for creating
extensions (UNO components) for LibreOffice.  To set the build environment for
building against the sdk use %{sdkinstdir}/setsdkenv_unix.sh.

%package sdk-doc
Summary: Software Development Kit documentation for LibreOffice
Group: Documentation
Requires: %{name}-sdk = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-sdk-doc < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-sdk-doc = 1:3.3.0
Provides: openoffice.org-sdk-doc%{?_isa} = 1:3.3.0
%endif

%description sdk-doc
This provides documentation for programming using the LibreOffice APIs
and examples of creating extensions (UNO components) for LibreOffice.

%package headless
Summary: LibreOffice Headless plug-in
Group: Development/Libraries
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-headless < 1:3.3.1
%if 0%{?rhel} && 0%{?rhel} < 7
Provides: openoffice.org-headless = 1:3.3.0
Provides: openoffice.org-headless%{?_isa} = 1:3.3.0
%endif

%description headless
A plug-in for LibreOffice that enables it to function without an X server. 
It implements the -headless command line option and allows LibreOffice to be
used as a backend server for e.g. document conversion.

%package glade
Summary: Support for creating LibreOffice dialogs in glade
Group: Development/Libraries
Requires: %{name}-ure = %{epoch}:%{version}-%{release}
Requires: %{name}-core = %{epoch}:%{version}-%{release}
Requires: glade3-libgladeui

%description glade
%{name}-glade contains a catalog of LibreOffice-specific widgets for
glade and ui-previewer tool to check the visual appearance of dialogs.

%package librelogo
Summary: LibreLogo scripting language
Group: Applications/Productivity
Requires: %{name}-writer = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno = %{epoch}:%{version}-%{release}

%description librelogo
Enables LibreLogo scripting in Writer. LibreLogo is a Logo-like
programming language with interactive vectorgraphics for education and
DTP.

%if 0%{?fedora}

%package kde
Summary: LibreOffice KDE integration plug-in
Group:   Applications/Productivity
Requires: %{name}-core = %{epoch}:%{version}-%{release}

%description kde
A plug-in for LibreOffice that enables integration into the KDE desktop environment.

%endif

%if 0%{?_enable_debug_packages}

%define debug_package %{nil}
%global __debug_package 1

%package debuginfo
Summary: Debug information for package %{name}
Group: Development/Debug
AutoReqProv: 0
%if 0%{?fedora}
Requires: libreoffice-core = %{epoch}:%{version}-%{release}
Recommends: libreoffice-gdb-debug-support = %{epoch}:%{version}-%{release}
%endif

%description debuginfo
This package provides debug information for package %{name}.
Debug information is useful when developing applications that use this
package or when debugging this package.

%files debuginfo -f debugfiles.list

%package gdb-debug-support
Summary: Additional support for debugging with gdb
Group: Development/Debug
Requires: gdb
Requires: %{libo_python}-six
AutoReqProv: 0

%description gdb-debug-support
This package provides gdb pretty printers for package %{name}.

%files gdb-debug-support
%{_datadir}/gdb/auto-load%{baseinstdir}
%{_datadir}/libreoffice/gdb

%endif

%define _langpack_common() \
%{baseinstdir}/program/resource/*%{1}.res  \
%{baseinstdir}/share/config/soffice.cfg/modules/*/ui/res/%{1}.zip \
%{baseinstdir}/share/config/soffice.cfg/*/ui/res/%{1}.zip \
%{baseinstdir}/share/template/%{1} \
%{baseinstdir}/share/registry/Langpack-%{1}.xcd \
%{baseinstdir}/share/registry/res/registry_%{1}.xcd \
%{baseinstdir}/share/registry/res/fcfg_langpack_%{1}.xcd \
%{nil}

# Defines a language pack subpackage.
#
# It's necessary to define language code (-l) and language name (-n).
# Additionally, it's possible
# * to require autocorr, hunspell, hyphen or mythes package or font for
#   given language,
# * to obsolete openoffice.org-langpack package,
# * to provide libreoffice-langpack-loc package, where loc is glibc
#   locale--this is necessary for yum to pick it automatically,
# * to require other, unrelated, packages,
# * to specify file serving as file list.
# For these, lower case character argument takes an argument specifying
# language, upper case character argument uses language from -l.
#
# All remaining arguments are considered to be files and added to the file
# list.
#
# Aa:  autocorr dependency
# c:   additional config file (just the name stem)
# E    the package does not contain any files (i.e., has empty filelist)
# Ff:  font language dependency
# Hh:  hunspell dependency
# i:   additional language added to this package
# L:   internal (LibreOffice) language code, used in file names
# l:   language code, e.g., cs
# Mm:  mythes dependency
# n:   language name, e.g., Czech
# Oo:  Obsoletes: of openoffice.org-langpack
# Vv:  Very archaic Obsoletes: of openoffice.org-langpack
# Ww:  Archaic Obsoletes: of openoffice.org2-langpack
# p:   Provides: of libreoffice-langpack
# r:   comma-separated list of additional requires
# S:s: script classification (cjk, ctl). -S is only a marker, as it does
#      not add any .xcd into the package (the file does not exist for at
#      least one CTL-using locale, si)
# T    has help files
# Xx:  has autotext definitions
# Yy:  hyphen dependency
#
# Example:
# libreoffice-langpack-cs: langpack for Czech lang. requiring hyphen-cs,
# autocorr-cs, mythes-cs-CZ and suitable font, obsoleting
# openoffice.org-langpack-cs_CZ:
# %%langpack -l cs -n Czech -H -A -m cs-CZ
#  b de g  jk     q  tu    z BCD  G IJK  N PQR  U    Z0123456789
%define langpack(Aa:c:EFf:Hh:i:L:l:Mm:n:p:Oo:r:S:s:TVv:Ww:Xx:Yy:) \
%define lang %{-l:%{-l*}}%{!-l:%{error:Language code not defined}} \
%define _langpack_lang %{-L:%{-L*}}%{!-L:%{lang}} \
%define pkgname langpack-%{lang} \
%define langname %{-n:%{-n*}}%{!-n:%{error:Language name not defined}} \
\
%global langpack_langs %{langpack_langs} %{_langpack_lang} %{-i:%{-i*}} \
\
%package %{pkgname} \
Summary: %{langname} language pack for LibreOffice \
Group: Applications/Productivity \
Requires: %{name}-core = %{epoch}:%{version}-%{release} \
%{-a:Requires: autocorr-%{-a*}}%{!-a:%{-A:Requires: autocorr-%{lang}}} \
%{-f:Requires: font(:lang=%{-f*})}%{!-f:%{-F:Requires: font(:lang=%{lang})}} \
%{-h:Requires: hunspell-%{-h*}}%{!-h:%{-H:Requires: hunspell-%{lang}}} \
%{-m:Requires: mythes-%{-m*}}%{!-m:%{-M:Requires: mythes-%{lang}}} \
%{-y:Requires: hyphen-%{-y*}}%{!-y:%{-Y:Requires: hyphen-%{lang}}} \
%{-r:Requires: %{-r*}} \
%{-o:Obsoletes: openoffice.org-langpack-%{-o*} < 1:3.3.1}%{!-o:%{-O:Obsoletes: openoffice.org-langpack-%{lang} < 1:3.3.1}} \
%{-w:Obsoletes: openoffice.org2-langpack-%{-x*} < 1:3.0.0}%{!-x:%{-W:Obsoletes: openoffice.org2-langpack-%{lang} < 1:3.0.0}} \
%{-v:Obsoletes: openoffice.org-langpack-%{-v*} < 1:2.0.3}%{!-v:%{-V:Obsoletes: openoffice.org-langpack-%{lang} < 1:2.0.3}} \
%{-p:Provides: %{name}-langpack-%{-p*}} \
\
%description %{pkgname} \
Provides additional %{langname} translations and resources for LibreOffice. \
\
%files %{pkgname} \
%{!-E: \
%{expand:%%_langpack_common %{_langpack_lang}} \
%{-x:%{baseinstdir}/share/autotext/%{-x*}}%{!-x:%{-X:%{baseinstdir}/share/autotext/%{_langpack_lang}}} \
%{-c:%{baseinstdir}/share/registry/%{-c*}.xcd} \
%{-s:%{baseinstdir}/share/registry/%{-s*}_%{_langpack_lang}.xcd} \
%{-T: \
%docdir %{baseinstdir}/help/%{_langpack_lang} \
%{baseinstdir}/help/%{_langpack_lang} \
} \
%{-i:%{expand:%%_langpack_common %{-i*}}} \
} \
%{nil}

# Defines an auto-correction subpackage.
#
# i: add autocorrections from additional language
# l: language code
# n: language name
# L  the filename does not contain country code
#
# All remaining arguments are considered to be files and added to the file
# list.
%define autocorr(i:Ll:n:) \
%define lang %{-l:%{-l*}}%{!-l:%{error:Language code not defined}} \
%define pkgname autocorr-%{lang} \
%define langname %{-n:%{-n*}}%{!-n:%{error:Language name not defined}} \
\
%package -n %{pkgname} \
Summary: %{langname} auto-correction rules \
Group: Applications/Text \
BuildArch: noarch \
\
%description -n %{pkgname} \
Rules for auto-correcting common %{langname} typing errors. \
\
%files -n %{pkgname} \
%doc instdir/LICENSE \
%dir %{_datadir}/autocorr \
%{-L:%{_datadir}/autocorr/acor_%{lang}.dat} \
%{!-L:%{_datadir}/autocorr/acor_%{lang}-*.dat} \
%{-i:%{_datadir}/autocorr/acor_%{-i*}-*.dat} \
%{nil}

%langpack -l en -n English -F -H -Y -M -A -E -L en-US -O

%if %{with langpacks}

%langpack -l af -n Afrikaans -F -H -Y -A -o af_ZA -V -w af_ZA
%langpack -l ar -n Arabic -F -H -s ctl -O -W
%langpack -l as -n Assamese -F -H -Y -o as_IN -w as_IN
%langpack -l bg -n Bulgarian -F -H -Y -M -A -T -X -o bg_BG -V -w bg_BG
%langpack -l bn -n Bengali -F -H -Y -T -O -v bn_IN -W
%if 0%{?fedora} || 0%{?rhel} >= 7
%langpack -l br -n Breton -F -H
%endif
%langpack -l ca -n Catalan -F -H -Y -M -A -T -o ca_ES -V -w ca_ES -X
%langpack -l cs -n Czech -F -H -Y -M -A -T -X -o cs_CZ -V -w cs_CZ
%langpack -l cy -n Welsh -F -H -Y -o cy_GB -V -w cy_GB
%langpack -l da -n Danish -F -H -Y -M -A -T -X -o da_DK -V -w da_DK
%langpack -l de -n German -F -H -Y -M -A -T -X -O -W
%langpack -l dz -n Dzongkha -F -s ctl -T -O
%langpack -l el -n Greek -F -H -Y -M -T -o el_GR -V -w el_GR
%langpack -l es -n Spanish -F -H -Y -M -A -T -X -O -W
%langpack -l et -n Estonian -F -H -Y -T -o et_EE -V -w et_EE
%langpack -l eu -n Basque -F -H -Y -T -o eu_ES -V -w eu_ES
%if 0%{?fedora} || 0%{?rhel} >= 7
%langpack -l fa -n Farsi -A -H -Y -s ctl -X
%endif
%if 0%{?rhel} && 0%{?rhel} < 7
%langpack -l fi -n Finnish -F -A -T -o fi_FI -V -w fi_FI -X
%else
%langpack -l fi -n Finnish -F -r libreoffice-voikko -A -T -o fi_FI -V -w fi_FI -X
%endif
%langpack -l fr -n French -F -H -Y -M -A -T -X -O -W
%langpack -l ga -n Irish -F -H -Y -M -A -o ga_IE -w ga_IE
%langpack -l gl -n Galician -F -H -Y -T -o gl_ES -V -w gl_ES
%langpack -l gu -n Gujarati -F -H -Y -s ctl -o gu_IN -w gu_IN -T
%langpack -l he -n Hebrew -F -H -s ctl -o he_IL -V -w he_IL -T
%langpack -l hi -n Hindi -F -H -Y -s ctl -T -o hi_IN -v hi-IN -w hi_IN -X
%langpack -l hr -n Croatian -F -H -Y -A -o hr_HR -V -w hr_HR -T -X
%langpack -l hu -n Hungarian -F -H -Y -M -A -T -X -o hu_HU -V -w hu_HU
%langpack -l it -n Italian -F -H -Y -M -A -T -X -O -W
%langpack -l ja -n Japanese -F -A -s cjk -T -X -o ja_JP -V -w ja_JP
%if 0%{?fedora} || 0%{?rhel} >= 7
%langpack -l kk -n Kazakh -F -H
%endif
%langpack -l kn -n Kannada -F -H -Y -o kn_IN -w ka_IN
%langpack -l ko -n Korean -F -H -A -s cjk -T -c korea -X -o ko_KR -V -w ko_KR
%langpack -l lt -n Lithuanian -F -H -Y -A -o lt_LT -V -w lt_LT -X
%if 0%{?fedora} || 0%{?rhel} >= 7
%langpack -l lv -n Latvian -F -H -Y -M
%endif
%langpack -l mai -n Maithili -F -o mai_IN
%if 0%{?rhel} && 0%{?rhel} < 7
%langpack -l ms -n Malay -F -H -o ms_MY
%endif
%langpack -l ml -n Malayalam -F -H -Y -o ml_IN -w ml_IN
%langpack -l mr -n Marathi -F -H -Y -o mr_IN -w mr_IN
%langpack -l nb -n Bokmal -F -H -Y -M -T -o nb_NO -V -w nb_NO
%langpack -l nl -n Dutch -F -H -Y -M -A -T -X -O -W
%langpack -l nn -n Nynorsk -F -H -Y -M -T -o nn_NO -V -w nn_NO
%define langpack_lang Southern Ndebele
%langpack -l nr -n %{langpack_lang} -F -H -o nr_ZA
%define langpack_lang Northern Sotho
%langpack -l nso -n %{langpack_lang} -F -H -o nso_ZA -w nso_ZA
%langpack -l or -n Odia -F -H -Y -s ctl -o or_IN -w or_IN
%langpack -l pa -n Punjabi -F -H -Y -s ctl -L pa-IN -O -v pa_IN -w pa_IN
%langpack -l pl -n Polish -F -H -Y -M -A -T -X -o pl_PL -V -w pl_PL
%define langpack_lang Brazilian Portuguese
%langpack -l pt-BR -n %{langpack_lang} -f pt -h pt -y pt -m pt -a pt -p pt_BR -T -X -o pt_BR -V -w pt_BR
%langpack -l pt-PT -n Portuguese -f pt -h pt -y pt -m pt -a pt -p pt_PT -T -L pt -x pt -o pt_PT -v pt -W
%langpack -l ro -n Romanian -A -F -H -Y -M -O -X
%langpack -l ru -n Russian -F -H -Y -M -A -T -X -O -W
%if 0%{?fedora} || 0%{?rhel} >= 7
%langpack -l si -n Sinhalese -F -H -S ctl -T -O
%endif
%langpack -l sk -n Slovak -F -H -Y -M -A -T -X -o sk_SK -V -w sk_SK
%langpack -l sl -n Slovenian -F -H -Y -M -A -T -X -o sl_SI -V -w sl_SI
%{baseinstdir}/share/wordbook/sl.dic

#rhbz#452379 clump serbian translations together
%langpack -l sr -n Serbian -F -H -Y -A -i sr-Latn -O -v sr_CS -w sr_CS
%langpack -l ss -n Swati -F -H -o ss_ZA
%define langpack_lang Southern Sotho
%langpack -l st -n %{langpack_lang} -F -H -o st_ZA
%langpack -l sv -n Swedish -F -H -Y -M -A -T -X -O -W
%langpack -l ta -n Tamil -F -H -Y -s ctl -o ta_IN -w ta_IN
%langpack -l te -n Telugu -F -H -Y -o te_IN -w te_IN
%langpack -l th -n Thai -F -H -s ctl -c ctlseqcheck_th -o th_TH -V -w th_TH
%langpack -l tn -n Tswana -F -H -o tn_ZA -V -w tn_ZA
%langpack -l tr -n Turkish -F -A -T -X -o tr_TR -V -W
%langpack -l ts -n Tsonga -F -H -o ts_ZA -V -w ts_ZA
%langpack -l uk -n Ukrainian -F -H -Y -M -T -O
%if 0%{?rhel} && 0%{?rhel} < 7
%langpack -l ur -n Urdu -F -H -O -W
%endif
%langpack -l ve -n Venda -F -H -o ve_ZA
%langpack -l xh -n Xhosa -F -H -o xh_ZA
%define langpack_lang Simplified Chinese
%langpack -l zh-Hans -n %{langpack_lang} -f zh-cn -a zh -p zh_CN -s cjk -T -L zh-CN -x zh-CN -o zh_CN -v zh-CN -w zh_CN
%define langpack_lang Traditional Chinese
%langpack -l zh-Hant -n %{langpack_lang} -f zh-tw -a zh -p zh_TW -s cjk -T -L zh-TW -x zh-TW -o zh_TW -v zh-TW -w zh_TW
%langpack -l zu -n Zulu -F -H -Y -o zu_ZA -V -w zu_ZA
%undefine langpack_lang

%endif

%autocorr -l en -n English

%if %{with langpacks}

%autocorr -l af -n Afrikaans
%autocorr -l bg -n Bulgarian
%autocorr -l ca -n Catalan
%autocorr -l cs -n Czech
%autocorr -l da -n Danish
%autocorr -l de -n German -L
%autocorr -l es -n Spanish -L
%autocorr -l fa -n Farsi
%autocorr -l fi -n Finnish
%autocorr -l fr -n French -L
%autocorr -l ga -n Irish
%autocorr -l hr -n Croatian
%autocorr -l hu -n Hungarian
%autocorr -l is -n Icelandic
%autocorr -l it -n Italian -L
%autocorr -l ja -n Japanese
%autocorr -l ko -n Korean
%autocorr -l lb -n Luxembourgish
%autocorr -l lt -n Lithuanian
%autocorr -l mn -n Mongolian
%autocorr -l nl -n Dutch
%autocorr -l pl -n Polish
%autocorr -l pt -n Portuguese
%autocorr -l ro -n Romanian
%autocorr -l ru -n Russian
%autocorr -l sk -n Slovak
%autocorr -l sl -n Slovenian
#rhbz#452379 clump serbian autocorrections together
%autocorr -l sr -n Serbian -i sr-Latn
%autocorr -l sv -n Swedish
%autocorr -l tr -n Turkish
%autocorr -l vi -n Vietnamese
%autocorr -l zh -n Chinese

%endif

%define make_autocorr_aliases(l:) \
%{?-l: \
for lang in %{*}; do \
    ln -sf acor_%{-l*}.dat acor_$lang.dat \
done \
} \
%{!?-l:%{error:-l must be present}}

%prep
%setup -q -n %{name}-%{version}%{?libo_prerelease} -b 1 -b 2
rm -rf git-hooks */git-hooks

# set up git repo
git init
git config user.name rpmbuild
git config user.email rpmbuild@fedoraproject.org
git config gc.auto 0 # disable auto packing
git add -A
git commit -q -a -m %{name}-%{version}

#Customize Palette to add Red Hat colours
(head -n -1 extras/source/palettes/standard.soc && \
 echo -e '  <draw:color draw:name="Red Hat 1" draw:color="#cc0000"/>
  <draw:color draw:name="Red Hat 2" draw:color="#0093d9"/>
  <draw:color draw:name="Red Hat 3" draw:color="#ff8d00"/>
  <draw:color draw:name="Red Hat 4" draw:color="#abb400"/>
  <draw:color draw:name="Red Hat 5" draw:color="#4e376b"/>' && \
 tail -n 1 extras/source/palettes/standard.soc) > redhat.soc
mv -f redhat.soc extras/source/palettes/standard.soc
git commit -q -a -m 'add Red Hat colors to palette'

# apply patches
git am %{patches}

%if 0%{?rhel} && 0%{?rhel} < 7
cp -r translations/source/en-GB translations/source/ms
cp -r translations/source/en-GB translations/source/ur
git add -A
git commit -q -a -m 'fix translations'
%endif

# Seeing .git dir makes some of the build tools change their behavior.
# We do not want that. Note: it is still possible to use
# git --git-dir=.git-rpm
mv .git .git-rpm

%build
echo build start time is `date`, diskspace: `df -h . | tail -n 1`
echo building localizations: %{langpack_langs}
# path to external tarballs
EXTSRCDIR=`dirname %{SOURCE0}`

%if 0%{?fedora}
# KDE bits
export QT4DIR=%{_qt4_prefix}
export KDE4DIR=%{_kde4_prefix}
export PATH=$QT4DIR/bin:$PATH
%endif

#use the RPM_OPT_FLAGS but remove the OOo overridden ones
for i in $RPM_OPT_FLAGS; do
        case "$i" in
                -pipe|-Wall|-Werror*|-g|-fexceptions) continue;;
        esac
        ARCH_FLAGS="$ARCH_FLAGS $i"
done
export ARCH_FLAGS
export CFLAGS=$ARCH_FLAGS
export CXXFLAGS=$ARCH_FLAGS

%if 0%{?rhel}
%if 0%{?rhel} < 7
# make segfaults on parallel build
%define distrooptions --disable-eot --disable-gltf --disable-firebird-sdbc --disable-graphite --without-junit --enable-gstreamer-0-10 --disable-gstreamer --disable-postgresql-sdbc --enable-python=system --with-system-hsqldb --without-doxygen --with-parallelism=-j1

%ifarch s390 s390x
%define archoptions --disable-sdremote-bluetooth
%endif
%else # rhel7
%define distrooptions --disable-eot --disable-gltf --disable-firebird-sdbc --disable-gstreamer-0-10 --enable-gstreamer --with-system-mythes --enable-python=system %{?_smp_mflags:--with-parallelism=%{_smp_mflags}}
%endif
%else # fedora
%define distrooptions --enable-eot --enable-kde4 --disable-gstreamer-0-10 --enable-gstreamer --with-system-mythes --with-system-libgltf --with-system-opencollada %{?_smp_mflags:--with-parallelism=%{_smp_mflags}}
export OPENCOLLADA_CFLAGS='-I/usr/include/COLLADABaseUtils -I/usr/include/COLLADAFramework -I/usr/include/COLLADASaxFrameworkLoader -I/usr/include/GeneratedSaxParser'
export OPENCOLLADA_LIBS='-lOpenCOLLADABaseUtils -lOpenCOLLADAFramework -lOpenCOLLADASaxFrameworkLoader -lGeneratedSaxParser'
%endif

%if %{with langpacks}
%define with_lang --with-lang='%{langpack_langs}'
%endif

%if ! 0%{libo_use_python3}
export PYTHON=%{_bindir}/python
%if 0%{?fedora} || 0%{?rhel} >= 7
export PYTHON_CFLAGS=`pkg-config --cflags python`
export PYTHON_LIBS=`pkg-config --libs python`
%else
export PYTHON_CFLAGS=`python-config --cflags python`
export PYTHON_LIBS=`python-config --libs python`
%endif
%endif

# %%if 0%%{?rhel} && 0%%{?rhel} < 7
aclocal -I m4
autoconf
# %endif

# TODO: enable coinmp?
# avoid running autogen.sh on make
touch autogen.lastrun
%configure \
 %vendoroption \
 %{?with_lang} \
 --disable-coinmp \
 --disable-fetch-external \
 --disable-gnome-vfs \
 --disable-openssl \
 --enable-evolution2 \
 --enable-ext-nlpsolver \
 --enable-ext-wiki-publisher \
 --enable-release-build \
 --enable-scripting-beanshell \
 --enable-scripting-javascript \
 --enable-symbols \
 --with-build-version="%{version}-%{release}" \
 --with-external-dict-dir=/usr/share/myspell \
 --with-external-tar="$EXTSRCDIR" \
 --with-help \
 --with-system-dicts \
 --with-system-libs \
 --with-system-ucpp \
 --without-fonts \
 --without-ppds \
 --without-system-npapi-headers \
 --with-gdrive-client-secret="GYWrDtzyZQZ0_g5YoBCC6F0I" \
 --with-gdrive-client-id="457862564325.apps.googleusercontent.com" \
 %{distrooptions} \
 %{?bundling_options} \
 %{?archoptions}

ulimit -c unlimited
make VERBOSE=true

#generate the icons and mime type stuff
export DESTDIR=../output
export KDEMAINDIR=/usr
export GNOMEDIR=/usr
export GNOME_MIME_THEME=hicolor
# TODO use empty variables? Should make the renaming hacks in %%install
# unnecessary.
. ./bin/get_config_variables PRODUCTVERSIONSHORT PRODUCTVERSION WORKDIR
pushd $WORKDIR/CustomTarget/sysui/share/libreoffice
./create_tree.sh
popd
mkdir $WORKDIR/os-integration
cp -pr $WORKDIR/CustomTarget/sysui/share/output/usr/share/* $WORKDIR/os-integration

%if %{with smallbuild}
# remove the biggest offenders
# NOTE: not removing complete LinkTarget, as some libs are needed for smoketest
rm -rf $WORKDIR/CxxObject $WORKDIR/GenCxxObject $WORKDIR/HelpTarget $WORKDIR/LinkTarget/CppunitTest
%endif

echo build end time is `date`, diskspace: `df -h . | tail -n 1`


%install
# TODO investigate use of make distro-pack-install
#figure out the icon version
. ./bin/get_config_variables PRODUCTVERSIONSHORT PRODUCTVERSION SRCDIR WORKDIR
export PRODUCTVERSIONSHORT PRODUCTVERSION

# installation

install -m 0755 -d %{buildroot}%{instdir}
if ! make instsetoo_native PKGFORMAT=installed EPM=not-used-but-must-be-set; then
    echo - ---dump log start---
    cat $WORKDIR/installation/LibreOffice/installed/logging/en-US/log_*_en-US.log
    echo - ---dump log end---
    echo - ---dump log start -- SDK---
    cat $WORKDIR/installation/LibreOffice_SDK/installed/logging/en-US/log_*_en-US.log
    echo - ---dump log end -- SDK---
    echo - ---dump log start -- languagepacks---
    cat $WORKDIR/installation/LibreOffice_languagepack/installed/logging/en-US/log_*_en-US.log
    echo - ---dump log end -- languagepacks---
    exit 1
fi
install -m 0755 -d %{buildroot}%{baseinstdir}
mv $WORKDIR/installation/LibreOffice/installed/install/en-US/* %{buildroot}%{baseinstdir}
%if %{with langpacks}
for langpack in $WORKDIR/installation/LibreOffice_languagepack/installed/install/*; do
  [ `basename $langpack` = log ] && continue
  cp -rp $langpack/* %{buildroot}%{baseinstdir}
  rm -rf $langpack
done
%endif
mv $WORKDIR/installation/LibreOffice_SDK/installed/install/en-US/sdk %{buildroot}%{sdkinstdir}
chmod -R +w %{buildroot}%{baseinstdir}

# postprocessing and tweaks

# The installer currently sets UserInstallation to
# $ORIGIN/../libreoffice/4, which is of course total nonsense. Because I
# have no inclination to crawl through mountains of perl code to figure out
# where it comes from, I am just going to replace it by a sensible
# value here.
sed -i -e '/UserInstallation/s@\$ORIGIN/..@$SYSUSERCONFIG@' %{buildroot}%{baseinstdir}/program/bootstraprc

#configure sdk
pushd %{buildroot}%{sdkinstdir}
    sed -e "s,@OO_SDK_NAME@,sdk," \
        -e "s,@OO_SDK_HOME@,%{sdkinstdir}," \
        -e "s,@OFFICE_HOME@,%{baseinstdir}," \
        -e "s,@OO_SDK_URE_HOME@,%{ureinstdir}," \
        -e "s,@OO_SDK_MAKE_HOME@,/usr/bin," \
        -e "s,@OO_SDK_ZIP_HOME@,/usr/bin," \
        -e "s,@OO_SDK_CPP_HOME@,/usr/bin," \
        -e "s,@OO_SDK_CC_55_OR_HIGHER@,," \
        -e "s,@OO_SDK_JAVA_HOME@,$JAVA_HOME," \
        -e "s,@OO_SDK_OUTPUT_DIR@,\$HOME," \
        -e "s,@SDK_AUTO_DEPLOYMENT@,NO," \
        setsdkenv_unix.sh.in > setsdkenv_unix.sh
    chmod 755 setsdkenv_unix.sh
    # we don't want to install the input file
    rm -f setsdkenv_unix.sh.in
# TODO: is this still necessary?
#fix permissions
    find examples -type f -exec chmod -x {} \;
popd

#ensure a template dir for each lang
pushd %{buildroot}%{baseinstdir}/share/template
for I in %{langpack_langs}; do
    mkdir -p $I
done
popd

#Set some aliases to canonical autocorrect language files for locales with matching languages
pushd %{buildroot}%{baseinstdir}/share/autocorr

%make_autocorr_aliases -l en-GB en-AG en-AU en-BS en-BW en-BZ en-CA en-DK en-GH en-HK en-IE en-IN en-JM en-NG en-NZ en-SG en-TT
%make_autocorr_aliases -l en-US en-PH
#en-ZA exists and has a good autocorrect file with two or three extras that make sense for 
#neighbouring english speaking territories
%make_autocorr_aliases -l en-ZA en-NA en-ZW
%if %{with langpacks}
%make_autocorr_aliases -l af-ZA af-NA
%make_autocorr_aliases -l nl-NL nl-AW
%make_autocorr_aliases -l sv-SE sv-FI
%else
rm -f acor_[a-df-z]*.dat acor_e[su]*.dat
%endif
popd
#rhbz#484055 make these shared across multiple applications
install -m 0755 -d %{buildroot}%{_datadir}
mv -f %{buildroot}%{baseinstdir}/share/autocorr %{buildroot}%{_datadir}/autocorr
chmod 755 %{buildroot}%{_datadir}/autocorr
ln -s %{_datadir}/autocorr %{buildroot}%{baseinstdir}/share/autocorr

#remove it in case we didn't build with gcj
rm -f %{buildroot}%{baseinstdir}/program/classes/sandbox.jar

#remove dummy .dat files
rm -f %{buildroot}%{baseinstdir}/program/root?.dat

#set standard permissions for rpmlint
find %{buildroot}%{baseinstdir} -exec chmod +w {} \;
find %{buildroot}%{baseinstdir} -type d -exec chmod 0755 {} \;

# move python bits into site-packages
install -m 0755 -d %{buildroot}%{libo_python_sitearch}
pushd %{buildroot}%{libo_python_sitearch}
echo "import sys, os" > uno.py
echo "sys.path.append('%{baseinstdir}/program')" >> uno.py
echo "os.putenv('URE_BOOTSTRAP', 'vnd.sun.star.pathname:%{baseinstdir}/program/fundamentalrc')" >> uno.py
cat %{buildroot}%{baseinstdir}/program/uno.py >> uno.py
rm -f %{buildroot}%{baseinstdir}/program/uno.py*
mv -f %{buildroot}%{baseinstdir}/program/unohelper.py* .
mv -f %{buildroot}%{baseinstdir}/program/officehelper.py* .
popd

# rhbz#477435 package opensymbol separately
pushd %{buildroot}%{baseinstdir}/share/fonts/truetype
install -d -m 0755 %{buildroot}%{_fontdir}
install -p -m 0644 *.ttf %{buildroot}%{_fontdir}
popd
rm -rf %{buildroot}%{baseinstdir}/share/fonts

%if 0%{?rhel} && 0%{?rhel} < 7
# fix rpath for bundled libs
chrpath -r '$ORIGIN:$ORIGIN/../ure-link/lib' \
    %{buildroot}%{baseinstdir}/program/libmwaw-0.3.so.3 \
    %{buildroot}%{baseinstdir}/program/libodfgen-0.1.so.1 \
    %{buildroot}%{baseinstdir}/program/libraptor2-lo.so.0 \
    %{buildroot}%{baseinstdir}/program/librasqal-lo.so.3 \
    %{buildroot}%{baseinstdir}/program/librdf-lo.so.0 \
    %{buildroot}%{baseinstdir}/program/libwps-0.3.so.3
%endif

#ensure that no sneaky un-prelinkable, un-fpic or non executable shared libs 
#have snuck through
pic=0
executable=0
for foo in `find %{buildroot}%{instdir} -name "*" -exec file {} \;| grep ": ELF" | cut -d: -f 1` ; do
    chmod +wx $foo
    ls -asl $foo
    result=`readelf -d $foo | grep TEXTREL` || true
    if [ "$result" != "" ]; then
        echo "TEXTREL Warning: $foo is b0rked (-fpic missing)"
        pic=1
    fi
    result=`readelf -l $foo | grep GNU_STACK | grep RWE` || true
    if [ "$result" != "" ]; then
        echo "GNU_STACK Warning: $foo is b0rked (-noexecstack missing)"
        executable=1
    fi
done
if [ $pic == 1 ]; then false; fi
if [ $executable == 1 ]; then false; fi

#make up some /usr/bin scripts
install -m 0755 -d %{buildroot}%{_bindir}

pushd %{buildroot}%{_bindir}
echo \#\!/bin/sh > ooffice
echo exec libreoffice \"\$@\" >> ooffice
chmod a+x ooffice

echo \#\!/bin/sh > ooviewdoc
echo exec libreoffice --view \"\$@\" >> ooviewdoc
chmod a+x ooviewdoc

for app in base calc draw impress math writer; do
    echo \#\!/bin/sh > oo$app
    echo exec libreoffice --$app \"\$@\" >> oo$app
    chmod a+x oo$app
done

sed -e s/LAUNCHER/unopkg/g -e s/BRAND/libreoffice/g %{SOURCE4} > unopkg
chmod a+x unopkg

sed -e s/LAUNCHER/soffice/g -e s/BRAND/libreoffice/g %{SOURCE4} > libreoffice
chmod a+x libreoffice

# rhbz#499474 provide a /usr/bin/soffice for .recently-used.xbel
ln -s %{baseinstdir}/program/soffice soffice
# rhbz#499474 provide a /usr/bin/openoffice.org for backwards compat
ln -s libreoffice openoffice.org
%if 0%{?rhel} && 0%{?rhel} < 7
# rhbz#833512 provide a /usr/bin/openoffice.org-1.9, etc. for backwards compat
ln -s libreoffice openoffice.org-2.0
ln -s libreoffice openoffice.org-1.9
%endif
popd

pushd %{buildroot}%{baseinstdir}/share/xdg/
chmod u+w *.desktop
ICONVERSION=`echo $PRODUCTVERSION | sed -e 's/\.//'`
for file in *.desktop; do
    # rhbz#156677 remove the version from Name=
    # rhbz#156067 don't version the icons
    sed -i -e "s/ *$PRODUCTVERSION//g" \
        -e "s/$ICONVERSION//g" \
        -e "s/$PRODUCTVERSIONSHORT//g" \
        $file
done
# rhbz#156677 / rhbz#186515 do not show math and startcenter
sed -i -e /NoDisplay/s/false/true/ math.desktop startcenter.desktop
# relocate the .desktop and icon files
install -m 0755 -d %{buildroot}%{_datadir}/applications
for app in base calc draw impress math startcenter writer xsltfilter; do
    sed -i -e 's/\${UNIXBASISROOTNAME}/%{name}/' $app.desktop
    desktop-file-validate $app.desktop
    install -m 0644 -p $app.desktop %{buildroot}%{_datadir}/applications/libreoffice-$app.desktop
done
popd

pushd $WORKDIR/os-integration
#get rid of the gnome icons and other unneeded files
rm -rf icons/gnome applications application-registry

#relocate the rest of them
# rhbz#901346 512x512 icons are not used by anything
for icon in `find icons -path '*/512x512' -prune -o -type f -print`; do
    install -m 0755 -d %{buildroot}%{_datadir}/`dirname $icon`
    install -m 0644 -p $icon %{buildroot}%{_datadir}/`echo $icon | sed -e s@libreoffice$ICONVERSION-@libreoffice-@ | sed -e s@libreoffice$PRODUCTVERSION-@libreoffice-@`
done
install -m 0755 -d %{buildroot}%{_datadir}/mime-info
install -m 0644 -p mime-info/libreoffice$PRODUCTVERSION.keys %{buildroot}%{_datadir}/mime-info/libreoffice.keys
install -m 0644 -p mime-info/libreoffice$PRODUCTVERSION.mime %{buildroot}%{_datadir}/mime-info/libreoffice.mime
#add our mime-types, e.g. for .oxt extensions
install -m 0755 -d %{buildroot}%{_datadir}/mime/packages
install -m 0644 -p mime/packages/libreoffice$PRODUCTVERSION.xml %{buildroot}%{_datadir}/mime/packages/libreoffice.xml
popd

rm -rf %{buildroot}%{baseinstdir}/readmes
rm -rf %{buildroot}%{baseinstdir}/licenses

# to-do, remove this in libreoffice 4.4 when --without-ppds is gone, it'll do the right thing on its own then
install -m 0755 -d %{buildroot}%{baseinstdir}/share/psprint/driver
install -m 0644 -p vcl/unx/generic/printer/configuration/ppds/SGENPRT.PS %{buildroot}%{baseinstdir}/share/psprint/driver/SGENPRT.PS

# rhbz#452385 to auto have postgres in classpath if subsequently installed
sed -i -e "s#URE_MORE_JAVA_CLASSPATH_URLS.*#& file:///usr/share/java/postgresql-jdbc.jar#" %{buildroot}%{baseinstdir}/program/fundamentalrc

# move glade catalog to system glade dir
install -m 0755 -d %{buildroot}%{_datadir}/glade3/catalogs
mv %{buildroot}%{baseinstdir}/share/glade/libreoffice-catalog.xml %{buildroot}%{_datadir}/glade3/catalogs

# rhbz#1049543 install appdata
install -m 0755 -d %{buildroot}%{_datadir}/appdata
install -m 0644 -p sysui/desktop/appstream-appdata/*.appdata.xml %{buildroot}%{_datadir}/appdata

# install man pages
install -m 0755 -d %{buildroot}%{_mandir}/man1
install -m 0644 -p sysui/desktop/man/*.1 %{buildroot}%{_mandir}/man1
for app in oobase oocalc oodraw ooffice ooimpress oomath ooviewdoc oowriter openoffice.org soffice; do
    echo '.so man1/libreoffice.1' > $app.1
    install -m 0644 -p $app.1 %{buildroot}%{_mandir}/man1
done

export DESTDIR=%{buildroot}
make cmd cmd="install-gdb-printers -a %{_datadir}/gdb/auto-load%{baseinstdir} -c -i %{baseinstdir} -p %{_datadir}/libreoffice/gdb"
# Bytecompiling fails for this file: tl.pyo contains a hexdump.
rm -f \
    %{buildroot}%{_datadir}/gdb/auto-load%{baseinstdir}/program/libtllo.so-gdb.py \
    %{buildroot}%{_datadir}/libreoffice/gdb/libreoffice/tl.py


%check
# test on slow arm takes too long. We trust it works
ulimit -c unlimited
unset WITH_LANG
# work around flawed accessibility check
export JFW_PLUGIN_DO_NOT_CHECK_ACCESSIBILITY="1"
export OOO_TEST_SOFFICE=path:%{buildroot}%{baseinstdir}/program/soffice
%if 0%{?rhel} && 0%{?rhel} < 7
timeout 2h make smoketest.subsequentcheck
%else
timeout -k 5m 3h make smoketest.subsequentcheck
%endif
# we don't need this anymore
rm -f %{buildroot}%{baseinstdir}/program/classes/smoketest.jar

%files

%files filters

%files core
%dir %{baseinstdir}
%dir %{baseinstdir}/help
%docdir %{baseinstdir}/help/en-US
%dir %{baseinstdir}/help/en-US
%{baseinstdir}/help/en-US/default.css
%{baseinstdir}/help/en-US/err.html
%{baseinstdir}/help/en-US/highcontrast1.css
%{baseinstdir}/help/en-US/highcontrast2.css
%{baseinstdir}/help/en-US/highcontrastblack.css
%{baseinstdir}/help/en-US/highcontrastwhite.css
%{baseinstdir}/help/en-US/sbasic.*
%{baseinstdir}/help/en-US/schart.*
%{baseinstdir}/help/en-US/shared.*
%{baseinstdir}/help/idxcaption.xsl
%{baseinstdir}/help/idxcontent.xsl
%{baseinstdir}/help/main_transform.xsl
%{baseinstdir}/presets
%dir %{baseinstdir}/program
%{baseinstdir}/program/libbasprovlo.so
%{baseinstdir}/program/libcairocanvaslo.so
%{baseinstdir}/program/libcanvasfactorylo.so
%dir %{baseinstdir}/program/classes
%{baseinstdir}/program/classes/commonwizards.jar
%{baseinstdir}/program/classes/form.jar
%{baseinstdir}/program/classes/query.jar
%{baseinstdir}/program/classes/report.jar
%{baseinstdir}/program/classes/ScriptFramework.jar
%{baseinstdir}/program/classes/ScriptProviderForJava.jar
%{baseinstdir}/program/classes/table.jar
%{baseinstdir}/program/classes/unoil.jar
%{baseinstdir}/program/classes/XMergeBridge.jar
%{baseinstdir}/program/classes/xmerge.jar
%{baseinstdir}/program/libcmdmaillo.so
%{baseinstdir}/program/libdeployment.so
%{baseinstdir}/program/libdeploymentgui.so
%{baseinstdir}/program/libdlgprovlo.so
%{baseinstdir}/program/libexpwraplo.so
%{baseinstdir}/program/flat_logo.svg
%{baseinstdir}/program/libfps_officelo.so
%{baseinstdir}/program/gdbtrace
%{baseinstdir}/program/gengal
%{baseinstdir}/program/gengal.bin
%{baseinstdir}/program/gnome-open-url
%{baseinstdir}/program/gnome-open-url.bin
%{baseinstdir}/program/kde-open-url
%{baseinstdir}/program/libi18nsearchlo.so
%{baseinstdir}/program/libldapbe2lo.so
%{baseinstdir}/program/libacclo.so
%{baseinstdir}/program/libavmedia*.so
%{baseinstdir}/program/libbasctllo.so
%{baseinstdir}/program/libbiblo.so
%{baseinstdir}/program/libcached1.so
%{baseinstdir}/program/libcanvastoolslo.so
%{baseinstdir}/program/libchart*lo.so
%{baseinstdir}/program/libcollator_data.so
%{baseinstdir}/program/libcppcanvaslo.so
%{baseinstdir}/program/libctllo.so
%{baseinstdir}/program/libcuilo.so
%{baseinstdir}/program/libdbalo.so
%{baseinstdir}/program/libdbaselo.so
%{baseinstdir}/program/libdbaxmllo.so
%{baseinstdir}/program/libdbmmlo.so
%{baseinstdir}/program/libdbpool2.so
%{baseinstdir}/program/libdbtoolslo.so
%{baseinstdir}/program/libdbulo.so
%{baseinstdir}/program/libdeploymentmisclo.so
%{baseinstdir}/program/libdesktop_detectorlo.so
%{baseinstdir}/program/libdict_ja.so
%{baseinstdir}/program/libdict_zh.so
%{baseinstdir}/program/libdrawinglayerlo.so
%{baseinstdir}/program/libeditenglo.so
%{baseinstdir}/program/libembobj.so
%{baseinstdir}/program/libemboleobj.so
%{baseinstdir}/program/libevoab*.so
%{baseinstdir}/program/libevtattlo.so
%{baseinstdir}/program/libegilo.so
%{baseinstdir}/program/libemelo.so
%{baseinstdir}/program/libepblo.so
%{baseinstdir}/program/libepglo.so
%{baseinstdir}/program/libepplo.so
%{baseinstdir}/program/libepslo.so
%{baseinstdir}/program/libeptlo.so
%{baseinstdir}/program/liberalo.so
%{baseinstdir}/program/libetilo.so
%{baseinstdir}/program/libexplo.so
%if 0%{?fedora}
%{baseinstdir}/program/libfirebird_sdbclo.so
%endif
%{baseinstdir}/program/libicdlo.so
%{baseinstdir}/program/libicglo.so
%{baseinstdir}/program/libidxlo.so
%{baseinstdir}/program/libimelo.so
%{baseinstdir}/program/libindex_data.so
%{baseinstdir}/program/libipblo.so
%{baseinstdir}/program/libipdlo.so
%{baseinstdir}/program/libipslo.so
%{baseinstdir}/program/libiptlo.so
%{baseinstdir}/program/libipxlo.so
%{baseinstdir}/program/libiralo.so
%{baseinstdir}/program/libitglo.so
%{baseinstdir}/program/libitilo.so
%{baseinstdir}/program/libfilelo.so
%{baseinstdir}/program/libfilterconfiglo.so
%{baseinstdir}/program/libflatlo.so
%{baseinstdir}/program/libfrmlo.so
%if 0%{?rhel}
%{baseinstdir}/program/libGLEW.so.*
%{baseinstdir}/program/libmwaw-0.3.so.*
%{baseinstdir}/program/libodfgen-0.1.so.*
%{baseinstdir}/program/librevenge-0.0.so.*
%{baseinstdir}/program/libwps-0.3.so.*
%endif
%{baseinstdir}/program/libguesslanglo.so
%{baseinstdir}/program/libhelplinkerlo.so
%{baseinstdir}/program/libhyphenlo.so
%{baseinstdir}/program/libjdbclo.so
%{baseinstdir}/program/liblnglo.so
%{baseinstdir}/program/libloglo.so
%{baseinstdir}/program/liblocaledata_en.so
%{baseinstdir}/program/liblocaledata_es.so
%{baseinstdir}/program/liblocaledata_euro.so
%{baseinstdir}/program/liblocaledata_others.so
%{baseinstdir}/program/libmcnttype.so
%{baseinstdir}/program/libmorklo.so
%{baseinstdir}/program/libmozbootstraplo.so
%{baseinstdir}/program/libmsfilterlo.so
%{baseinstdir}/program/libmtfrendererlo.so
%{baseinstdir}/program/libmysqllo.so
%{baseinstdir}/program/libodbclo.so
%{baseinstdir}/program/liboglcanvaslo.so
%{baseinstdir}/program/liboffacclo.so
%{baseinstdir}/program/libooxlo.so
%{baseinstdir}/program/libpcrlo.so
%{baseinstdir}/program/libpdffilterlo.so
%{baseinstdir}/program/libpllo.so
%{baseinstdir}/program/libprotocolhandlerlo.so
%{baseinstdir}/program/libqstart_gtklo.so
%{baseinstdir}/program/librecentfile.so
%{baseinstdir}/program/libreslo.so
%{baseinstdir}/program/libsaxlo.so
%{baseinstdir}/program/libscnlo.so
%{baseinstdir}/program/libscriptframe.so
%{baseinstdir}/program/libsdlo.so
%{baseinstdir}/program/libsdfiltlo.so
%{baseinstdir}/program/libsdbc2.so
%{baseinstdir}/program/libsdbtlo.so
%{baseinstdir}/program/libsddlo.so
%{baseinstdir}/program/libsduilo.so
%{baseinstdir}/program/libspelllo.so
%{baseinstdir}/program/libsrtrs1.so
%{baseinstdir}/program/libstoragefdlo.so
%{baseinstdir}/program/libsvgiolo.so
%{baseinstdir}/program/libsvxlo.so
%{baseinstdir}/program/libsvxcorelo.so
%{baseinstdir}/program/libswdlo.so
%{baseinstdir}/program/libswlo.so
%{baseinstdir}/program/libtextconv_dict.so
%{baseinstdir}/program/libtextconversiondlgslo.so
%{baseinstdir}/program/libtextfdlo.so
%{baseinstdir}/program/libodfflatxmllo.so
# TODO: shouldn't it have lo suffix?
%{baseinstdir}/program/libucbhelper.so
%{baseinstdir}/program/libucpchelp1.so
%{baseinstdir}/program/libucpdav1.so
%{baseinstdir}/program/libucpftp1.so
%{baseinstdir}/program/libucphier1.so
%{baseinstdir}/program/libucppkg1.so
%{baseinstdir}/program/libunordflo.so
%{baseinstdir}/program/libunopkgapp.so
%{baseinstdir}/program/libunoxmllo.so
%{baseinstdir}/program/libuuilo.so
%{baseinstdir}/program/libvbahelperlo.so
%{baseinstdir}/program/libvclplug_genlo.so
%{baseinstdir}/program/libvclplug_gtklo.so
%{baseinstdir}/program/libxmlfalo.so
%{baseinstdir}/program/libxmlfdlo.so
%{baseinstdir}/program/libxoflo.so
%{baseinstdir}/program/libxsec_fw.so
%{baseinstdir}/program/libxsec_xmlsec.so
%{baseinstdir}/program/libxsltdlglo.so
%{baseinstdir}/program/libxsltfilterlo.so
%{baseinstdir}/program/libxstor.so
%if 0%{?fedora} || 0%{?rhel} >= 7
# TODO how useful this is in Fedora?
%{baseinstdir}/program/liblosessioninstalllo.so
%endif
%{baseinstdir}/program/libmigrationoo2lo.so
%{baseinstdir}/program/libmigrationoo3lo.so
%{baseinstdir}/program/libmsformslo.so
%{baseinstdir}/program/nsplugin
%{baseinstdir}/program/open-url
%{baseinstdir}/program/types/offapi.rdb
%{baseinstdir}/program/libpasswordcontainerlo.so
%{baseinstdir}/program/pagein-common
%{baseinstdir}/program/pluginapp.bin
%dir %{baseinstdir}/program/resource
%{baseinstdir}/program/resource/avmediaen-US.res
%{baseinstdir}/program/resource/accen-US.res
%{baseinstdir}/program/resource/basctlen-US.res
%{baseinstdir}/program/resource/biben-US.res
%{baseinstdir}/program/resource/chartcontrolleren-US.res
%{baseinstdir}/program/resource/cuien-US.res
%{baseinstdir}/program/resource/dbaen-US.res
%{baseinstdir}/program/resource/dbmmen-US.res
%{baseinstdir}/program/resource/dbuen-US.res
%{baseinstdir}/program/resource/dbwen-US.res
%{baseinstdir}/program/resource/deploymenten-US.res
%{baseinstdir}/program/resource/deploymentguien-US.res
%{baseinstdir}/program/resource/dkten-US.res
%{baseinstdir}/program/resource/editengen-US.res
%{baseinstdir}/program/resource/epsen-US.res
%{baseinstdir}/program/resource/euren-US.res
%{baseinstdir}/program/resource/fps_officeen-US.res
%{baseinstdir}/program/resource/frmen-US.res
%{baseinstdir}/program/resource/fween-US.res
%{baseinstdir}/program/resource/galen-US.res
%{baseinstdir}/program/resource/impen-US.res
%{baseinstdir}/program/resource/ofaen-US.res
%{baseinstdir}/program/resource/pcren-US.res
%{baseinstdir}/program/resource/pdffilteren-US.res
%{baseinstdir}/program/resource/sben-US.res
%{baseinstdir}/program/resource/scnen-US.res
%{baseinstdir}/program/resource/sden-US.res
%{baseinstdir}/program/resource/sfxen-US.res
%{baseinstdir}/program/resource/sdbten-US.res
%{baseinstdir}/program/resource/svlen-US.res
%{baseinstdir}/program/resource/svten-US.res
%{baseinstdir}/program/resource/svxen-US.res
%{baseinstdir}/program/resource/swen-US.res
%{baseinstdir}/program/resource/tplen-US.res
%{baseinstdir}/program/resource/uuien-US.res
%{baseinstdir}/program/resource/upden-US.res
%{baseinstdir}/program/resource/vclen-US.res
%{baseinstdir}/program/resource/wzien-US.res
%{baseinstdir}/program/resource/xmlsecen-US.res
%{baseinstdir}/program/resource/xsltdlgen-US.res
%{baseinstdir}/program/senddoc
%dir %{baseinstdir}/program/services
%{baseinstdir}/program/services/services.rdb
%{baseinstdir}/program/libsimplecanvaslo.so
%{baseinstdir}/program/libslideshowlo.so
%{baseinstdir}/program/libsofficeapp.so
%{baseinstdir}/program/libstringresourcelo.so
%{baseinstdir}/program/libsysshlo.so
%{baseinstdir}/program/libucpcmis1lo.so
%{baseinstdir}/program/libucpexpand1lo.so
%{baseinstdir}/program/libucpextlo.so
%{baseinstdir}/program/libucptdoc1lo.so
%{baseinstdir}/program/unorc
%{baseinstdir}/program/libupdatefeedlo.so
%{baseinstdir}/ure-link
%{baseinstdir}/program/uri-encode
%{baseinstdir}/program/libvbaeventslo.so
%{baseinstdir}/program/libvclcanvaslo.so
%{baseinstdir}/program/versionrc
%{baseinstdir}/program/xid-fullscreen-on-all-monitors
%dir %{baseinstdir}/share
%dir %{baseinstdir}/share/Scripts
%{baseinstdir}/share/Scripts/java
%{baseinstdir}/share/autocorr
%dir %{_datadir}/autocorr
%dir %{baseinstdir}/share/autotext
%{baseinstdir}/share/autotext/en-US
%{baseinstdir}/share/basic
%dir %{baseinstdir}/share/config
%{baseinstdir}/share/config/images.zip
%{baseinstdir}/share/config/images_crystal.zip
%{baseinstdir}/share/config/images_galaxy.zip
%{baseinstdir}/share/config/images_hicontrast.zip
%{baseinstdir}/share/config/images_oxygen.zip
%{baseinstdir}/share/config/images_sifr.zip
%{baseinstdir}/share/config/images_tango.zip
%dir %{baseinstdir}/share/config/soffice.cfg
%{baseinstdir}/share/config/soffice.cfg/modules
%if %{with langpacks}
# UI translations go into langpacks
%exclude %{baseinstdir}/share/config/soffice.cfg/modules/*/ui/res
%endif
%{baseinstdir}/share/config/soffice.cfg/*/ui
%if %{with langpacks}
# UI translations go into langpacks
%exclude %{baseinstdir}/share/config/soffice.cfg/*/ui/res
%endif
%{baseinstdir}/share/config/webcast
%{baseinstdir}/share/config/wizard
%dir %{baseinstdir}/share/dtd
%{baseinstdir}/share/dtd/officedocument
%{baseinstdir}/share/gallery
%dir %{baseinstdir}/share/labels
%{baseinstdir}/share/labels/labels.xml
%if 0%{?rhel} && 0%{?rhel} < 7
%{baseinstdir}/share/liblangtag
%endif
%dir %{baseinstdir}/share/psprint
%config %{baseinstdir}/share/psprint/psprint.conf
%{baseinstdir}/share/psprint/driver
%dir %{baseinstdir}/share/registry
%{baseinstdir}/share/registry/gnome.xcd
%{baseinstdir}/share/registry/lingucomponent.xcd
%{baseinstdir}/share/registry/main.xcd
%{baseinstdir}/share/registry/oo-ad-ldap.xcd.sample
%{baseinstdir}/share/registry/oo-ldap.xcd.sample
%{baseinstdir}/share/registry/Langpack-en-US.xcd
%dir %{baseinstdir}/share/registry/res
%{baseinstdir}/share/registry/res/fcfg_langpack_en-US.xcd
%dir %{baseinstdir}/share/template
%{baseinstdir}/share/template/en-US
%dir %{baseinstdir}/share/template/common
%{baseinstdir}/share/template/common/internal
%{baseinstdir}/share/template/common/layout
%{baseinstdir}/share/template/common/wizard
%{baseinstdir}/share/template/wizard
%dir %{baseinstdir}/share/wordbook
%{baseinstdir}/share/wordbook/en-GB.dic
%{baseinstdir}/share/wordbook/en-US.dic
%{baseinstdir}/share/wordbook/technical.dic
%{baseinstdir}/program/liblnthlo.so
%{_bindir}/unopkg
%{_mandir}/man1/unopkg.1*
#icons and mime
%{_datadir}/icons/*/*/*/libreoffice*
%{_datadir}/mime-info/libreoffice.*
%{baseinstdir}/program/libxmlsecurity.so
%{_datadir}/mime/packages/libreoffice.xml
%{baseinstdir}/program/libconfigmgrlo.so
%{baseinstdir}/program/libdesktopbe1lo.so
%{baseinstdir}/program/libfsstoragelo.so
%{baseinstdir}/program/libgconfbe1lo.so
%{baseinstdir}/program/libi18npoollo.so
%{baseinstdir}/program/libbasegfxlo.so
# TODO: shouldn't it have lo suffix?
%{baseinstdir}/program/libcomphelper.so
%{baseinstdir}/program/libfwelo.so
%{baseinstdir}/program/libfwilo.so
%{baseinstdir}/program/libfwklo.so
%{baseinstdir}/program/libfwllo.so
%{baseinstdir}/program/libfwmlo.so
%{baseinstdir}/program/libi18nlangtag.so
# TODO: shouldn't it have lo suffix?
%{baseinstdir}/program/libi18nutil.so
%{baseinstdir}/program/libpackage2.so
%{baseinstdir}/program/libsblo.so
%{baseinstdir}/program/libsfxlo.so
%{baseinstdir}/program/libsotlo.so
%{baseinstdir}/program/libspllo.so
%{baseinstdir}/program/libsvllo.so
%{baseinstdir}/program/libsvtlo.so
%{baseinstdir}/program/libtklo.so
%{baseinstdir}/program/libtllo.so
%{baseinstdir}/program/libucb1.so
%{baseinstdir}/program/libucpfile1.so
%{baseinstdir}/program/libutllo.so
%{baseinstdir}/program/libvcllo.so
%{baseinstdir}/program/libvclopengllo.so
%{baseinstdir}/program/libwriterperfectlo.so
%{baseinstdir}/program/libxmlscriptlo.so
%{baseinstdir}/program/libxolo.so
%{baseinstdir}/program/liblocalebe1lo.so
%{baseinstdir}/program/libucpgio1lo.so
%{baseinstdir}/program/types/oovbaapi.rdb
#share unopkg
%dir %{baseinstdir}/share/extensions
%{baseinstdir}/share/extensions/package.txt
%{baseinstdir}/program/unopkg
%{baseinstdir}/program/unopkg.bin
%{baseinstdir}/program/bootstraprc
%{baseinstdir}/program/fundamentalrc
%{baseinstdir}/program/setuprc
%doc %{baseinstdir}/CREDITS.fodt
%doc %{baseinstdir}/LICENSE
%doc %{baseinstdir}/LICENSE.html
%doc %{baseinstdir}/LICENSE.fodt
%doc %{baseinstdir}/NOTICE
%{baseinstdir}/program/intro.*
%{baseinstdir}/program/soffice
%{baseinstdir}/program/soffice.bin
%{baseinstdir}/program/sofficerc
%{baseinstdir}/program/unoinfo
%{baseinstdir}/program/libnpsoplugin.so
%{baseinstdir}/program/oosplash
%{baseinstdir}/program/shell/
%dir %{baseinstdir}/share/filter
%{baseinstdir}/share/filter/oox-drawingml-adj-names
%{baseinstdir}/share/filter/oox-drawingml-cs-presets
%{baseinstdir}/share/filter/vml-shape-types
%{baseinstdir}/share/xdg/
%{baseinstdir}/program/redirectrc
%{_datadir}/applications/libreoffice-startcenter.desktop
#launchers
%{_bindir}/libreoffice
%{_bindir}/openoffice.org
%if 0%{?rhel} && 0%{?rhel} < 7
%{_bindir}/openoffice.org-1.9
%{_bindir}/openoffice.org-2.0
%endif
%{_bindir}/soffice
%{_bindir}/ooffice
%{_bindir}/ooviewdoc
%if 0%{?rhel} && 0%{?rhel} < 7
%{baseinstdir}/program/libraptor2-lo.so.0
%{baseinstdir}/program/librasqal-lo.so.3
%{baseinstdir}/program/librdf-lo.so.0
%{baseinstdir}/program/libclucene.so
%{baseinstdir}/program/liblcms2.so.2
%{baseinstdir}/share/fingerprint
%endif
%{_mandir}/man1/libreoffice.1*
%{_mandir}/man1/openoffice.org.1*
%{_mandir}/man1/soffice.1*
%{_mandir}/man1/ooffice.1*
%{_mandir}/man1/ooviewdoc.1*

%post core
update-desktop-database %{_datadir}/applications &> /dev/null || :
for theme in hicolor locolor; do
    touch --no-create %{_datadir}/icons/$theme &>/dev/null || :
done
touch --no-create %{_datadir}/mime/packages &> /dev/null || :

%postun core
update-desktop-database %{_datadir}/applications &> /dev/null || :
if [ $1 -eq 0 ] ; then
    for theme in hicolor locolor; do
        touch --no-create %{_datadir}/icons/$theme &>/dev/null || :
        gtk-update-icon-cache -q %{_datadir}/icons/$theme &>/dev/null || :
    done
    touch --no-create %{_datadir}/mime/packages &> /dev/null || :
    update-mime-database %{?fedora:-n} %{_datadir}/mime &> /dev/null || :
fi

%posttrans core
for theme in hicolor locolor; do
    gtk-update-icon-cache -q %{_datadir}/icons/$theme &>/dev/null || :
done
update-mime-database %{?fedora:-n} %{_datadir}/mime &> /dev/null || :


%files base
%{baseinstdir}/help/en-US/sdatabase.*
%if 0%{?fedora} || 0%{?rhel} >= 7
%{baseinstdir}/program/classes/hsqldb.jar
%endif
%{baseinstdir}/program/classes/reportbuilder.jar
%{baseinstdir}/program/classes/reportbuilderwizard.jar
%{baseinstdir}/program/classes/sdbc_hsqldb.jar
%{baseinstdir}/program/libabplo.so
%{baseinstdir}/program/libdbplo.so
%{baseinstdir}/program/libhsqldb.so
%{baseinstdir}/program/librptlo.so
%{baseinstdir}/program/librptuilo.so
%{baseinstdir}/program/librptxmllo.so
%{baseinstdir}/program/resource/abpen-US.res
%{baseinstdir}/program/resource/cnren-US.res
%{baseinstdir}/program/resource/dbpen-US.res
%{baseinstdir}/program/resource/rpten-US.res
%{baseinstdir}/program/resource/rptuien-US.res
%{baseinstdir}/program/resource/sdbclen-US.res
%{baseinstdir}/program/resource/sdberren-US.res
%{baseinstdir}/share/registry/base.xcd
%{baseinstdir}/share/registry/reportbuilder.xcd
%{baseinstdir}/program/sbase
%{_datadir}/appdata/libreoffice-base.appdata.xml
%{_datadir}/applications/libreoffice-base.desktop
%{_bindir}/oobase
%{_mandir}/man1/oobase.1*

%post base
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun base
update-desktop-database %{_datadir}/applications &> /dev/null || :

%files bsh
%{baseinstdir}/program/classes/ScriptProviderForBeanShell.jar
%{baseinstdir}/program/services/scriptproviderforbeanshell.rdb
%{baseinstdir}/share/Scripts/beanshell

%files rhino
%{baseinstdir}/program/classes/js.jar
%{baseinstdir}/program/classes/ScriptProviderForJavaScript.jar
%{baseinstdir}/program/services/scriptproviderforjavascript.rdb
%{baseinstdir}/share/Scripts/javascript

%files wiki-publisher
%docdir %{baseinstdir}/share/extensions/wiki-publisher/license
%{baseinstdir}/share/extensions/wiki-publisher

%files nlpsolver
%docdir %{baseinstdir}/share/extensions/nlpsolver/help
%{baseinstdir}/share/extensions/nlpsolver

%files officebean
%{baseinstdir}/program/classes/officebean.jar
%{baseinstdir}/program/libofficebean.so

%files ogltrans
%{baseinstdir}/program/libOGLTranslo.so
%{baseinstdir}/share/config/soffice.cfg/simpress/transitions-ogl.xml
%{baseinstdir}/share/registry/ogltrans.xcd

%files pdfimport
%{baseinstdir}/program/libpdfimportlo.so
%{baseinstdir}/program/xpdfimport
%{baseinstdir}/share/registry/pdfimport.xcd
%dir %{baseinstdir}/share/xpdfimport
%{baseinstdir}/share/xpdfimport/xpdfimport_err.pdf

%_font_pkg -n %{fontname} opens___.ttf
%doc instdir/LICENSE

%files calc
%{baseinstdir}/help/en-US/scalc.*
%{baseinstdir}/program/libanalysislo.so
%{baseinstdir}/program/libcalclo.so
%{baseinstdir}/program/libdatelo.so
%{baseinstdir}/program/libforlo.so
%{baseinstdir}/program/libforuilo.so
%{baseinstdir}/program/libpricinglo.so
%{baseinstdir}/program/libsclo.so
%{baseinstdir}/program/libscdlo.so
%{baseinstdir}/program/libscfiltlo.so
%{baseinstdir}/program/libscopencllo.so
%{baseinstdir}/program/libscuilo.so
%{baseinstdir}/program/libsolverlo.so
%{baseinstdir}/program/libwpftcalclo.so
%{baseinstdir}/program/resource/analysisen-US.res
%{baseinstdir}/program/resource/dateen-US.res
%{baseinstdir}/program/resource/foren-US.res
%{baseinstdir}/program/resource/foruien-US.res
%{baseinstdir}/program/resource/pricingen-US.res
%{baseinstdir}/program/resource/scen-US.res
%{baseinstdir}/program/resource/solveren-US.res
%{baseinstdir}/program/libvbaobjlo.so
%{baseinstdir}/share/registry/calc.xcd
%{baseinstdir}/program/pagein-calc
%{baseinstdir}/program/scalc
%{_datadir}/appdata/libreoffice-calc.appdata.xml
%{_datadir}/applications/libreoffice-calc.desktop
%{_bindir}/oocalc
%{_mandir}/man1/oocalc.1*

%post calc
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun calc
update-desktop-database %{_datadir}/applications &> /dev/null || :

%files draw
%{baseinstdir}/help/en-US/sdraw.*
%{baseinstdir}/share/registry/draw.xcd
%{baseinstdir}/program/pagein-draw
%{baseinstdir}/program/sdraw
%{_datadir}/appdata/libreoffice-draw.appdata.xml
%{_datadir}/applications/libreoffice-draw.desktop
%{_bindir}/oodraw
%{_mandir}/man1/oodraw.1*

%post draw
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun draw
update-desktop-database %{_datadir}/applications &> /dev/null || :

%files emailmerge
%{baseinstdir}/program/mailmerge.py*
%{baseinstdir}/program/msgbox.py*

%files writer
%{baseinstdir}/help/en-US/swriter.*
%{baseinstdir}/program/libhwplo.so
%{baseinstdir}/program/liblwpftlo.so
%{baseinstdir}/program/libmswordlo.so
%{baseinstdir}/program/libswuilo.so
%{baseinstdir}/program/libt602filterlo.so
%{baseinstdir}/program/libwpftwriterlo.so
%{baseinstdir}/program/libwriterfilterlo.so
%{baseinstdir}/program/libvbaswobjlo.so
%{baseinstdir}/program/resource/t602filteren-US.res
%{baseinstdir}/share/registry/writer.xcd
%{baseinstdir}/program/pagein-writer
%{baseinstdir}/program/swriter
%{_datadir}/appdata/libreoffice-writer.appdata.xml
%{_datadir}/applications/libreoffice-writer.desktop
%{_bindir}/oowriter
%{_mandir}/man1/oowriter.1*

%post writer
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun writer
update-desktop-database %{_datadir}/applications &> /dev/null || :

%files impress
%{baseinstdir}/help/en-US/simpress.*
%{baseinstdir}/program/libanimcorelo.so
%{baseinstdir}/program/libplacewarelo.so
%{baseinstdir}/program/libPresentationMinimizerlo.so
%{baseinstdir}/program/libPresenterScreenlo.so
%{baseinstdir}/program/libwpftimpresslo.so
%dir %{baseinstdir}/share/config/soffice.cfg/simpress
%{baseinstdir}/share/config/soffice.cfg/simpress/effects.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/layoutlist.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/objectlist.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/transitions.xml
%{baseinstdir}/share/registry/impress.xcd
%{baseinstdir}/program/pagein-impress
%{baseinstdir}/program/simpress
%{_datadir}/appdata/libreoffice-impress.appdata.xml
%{_datadir}/applications/libreoffice-impress.desktop
%{_bindir}/ooimpress
%{_mandir}/man1/ooimpress.1*

%post impress
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun impress
update-desktop-database %{_datadir}/applications &> /dev/null || :

%files math
%{baseinstdir}/help/en-US/smath.*
%{baseinstdir}/program/libsmlo.so
%{baseinstdir}/program/libsmdlo.so
%{baseinstdir}/program/resource/smen-US.res
%{baseinstdir}/share/registry/math.xcd
%{baseinstdir}/program/smath
%{_datadir}/applications/libreoffice-math.desktop
%{_bindir}/oomath
%{_mandir}/man1/oomath.1*

%post math
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun math
update-desktop-database %{_datadir}/applications &> /dev/null || :

%files graphicfilter
%{baseinstdir}/program/libflashlo.so
%{baseinstdir}/program/libgraphicfilterlo.so
%{baseinstdir}/program/libsvgfilterlo.so
%{baseinstdir}/program/libwpftdrawlo.so
%{baseinstdir}/share/registry/graphicfilter.xcd

%files xsltfilter
%{baseinstdir}/share/xslt
%{baseinstdir}/share/registry/xsltfilter.xcd
%{_datadir}/applications/libreoffice-xsltfilter.desktop

%if 0%{?fedora} || 0%{?rhel} >= 7
%files postgresql
%{baseinstdir}/program/libpostgresql-sdbclo.so
%{baseinstdir}/program/libpostgresql-sdbc-impllo.so
%{baseinstdir}/program/postgresql-sdbc.ini
%{baseinstdir}/program/services/postgresql-sdbc.rdb
%{baseinstdir}/share/registry/postgresql.xcd
%endif

%files ure
%doc instdir/LICENSE
%{ureinstdir}

%files sdk
%{sdkinstdir}/
%exclude %{sdkinstdir}/docs/
%exclude %{sdkinstdir}/examples/

%files sdk-doc
%docdir %{sdkinstdir}/docs
%{sdkinstdir}/docs/
%{sdkinstdir}/examples/

%files headless
%{baseinstdir}/program/libbasebmplo.so
%{baseinstdir}/program/libvclplug_svplo.so

%files pyuno
%{baseinstdir}/program/libpyuno.so
%{baseinstdir}/program/pythonloader.py*
%{baseinstdir}/program/libpythonloaderlo.so
%{baseinstdir}/program/pythonloader.unorc
%{baseinstdir}/program/pythonscript.py*
%{baseinstdir}/program/pyuno.so
%{baseinstdir}/program/services/pyuno.rdb
%{baseinstdir}/program/services/scriptproviderforpython.rdb
%{baseinstdir}/program/wizards
%{baseinstdir}/share/Scripts/python
%exclude %{baseinstdir}/share/Scripts/python/LibreLogo
%{libo_python_sitearch}/uno.py*
%{libo_python_sitearch}/unohelper.py*
%{libo_python_sitearch}/officehelper.py*
%if 0%{libo_use_python3}
%{libo_python_sitearch}/__pycache__/uno.cpython-*
%{libo_python_sitearch}/__pycache__/unohelper.cpython-*
%{libo_python_sitearch}/__pycache__/officehelper.cpython-*
%endif
%{baseinstdir}/share/registry/pyuno.xcd

%files librelogo
%{baseinstdir}/share/registry/librelogo.xcd
%{baseinstdir}/share/Scripts/python/LibreLogo

%files glade
%{baseinstdir}/program/ui-previewer
%{_datadir}/glade3/catalogs/libreoffice-catalog.xml

%if 0%{?fedora}

%files kde
%{baseinstdir}/program/libkde4be1lo.so
%{baseinstdir}/program/libvclplug_kde4lo.so

%endif

%changelog
* Mon Nov 23 2015 David Tardon <dtardon@redhat.com> - 1:4.3.7.2-2
- Related: rhbz#1258467 fix RPATH for more bundled libs

* Thu Nov 05 2015 David Tardon <dtardon@redhat.com> - 1:4.3.7.2-1
- Resolves: rhbz#1258467 rebase to 4.3.x

* Mon May 25 2015 David Tardon <dtardon@redhat.com> - 1:4.2.8.2-11
- Resolves: rhbz#1223696 some labels in print dialog are not translated, even
  though the translations exist

* Fri May 01 2015 David Tardon <dtardon@redhat.com> - 1:4.2.8.2-10
- Resolves: rhbz#1217466 CVE-2015-1774 HWP filter fix

* Mon Apr 20 2015 David Tardon <dtardon@redhat.com> - 1:4.2.8.2-9
- Resolves: rhbz#1209852 enable accidentally disabled GIO UCP

* Wed Mar 18 2015 David Tardon <dtardon@redhat.com> - 1:4.2.8.2-8
- Related: rhbz#1150048 rpmdiff: avoid multilib conflict

* Mon Feb 09 2015 David Tardon <dtardon@redhat.com> - 1:4.2.8.2-7
- Related: rhbz#1150048 packaging fix

* Fri Feb 06 2015 David Tardon <dtardon@redhat.com> - 1:4.2.8.2-6
- Related: rhbz#1150048 rpmdiff fixes

* Thu Jan 29 2015 Caolán McNamara <caolanm@redhat.com> - 1:4.2.8.2-5
- Related: rhbz#1150048 fix some indic shortcuts

* Wed Jan 28 2015 Caolán McNamara <caolanm@redhat.com> - 1:4.2.8.2-4
- Resolves: rhbz#1150048 rebase to latest stable 4.2.8.2

* Tue Aug 19 2014 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-14
- Resolves: rhbz#1130264 crash in gstreamer callback on s390x
- Resolves: rhbz#1131428 cannot export charts as svg
- Resolves: rhbz#1035298 obsolete openoffice.org-langpack-ms_MY

* Thu May 15 2014 David Tardon <dtardon@redhat.com> - 1:4.0.4.2-13
- Related: rhbz#1035298 add some more requires and swdlo needs to be in core
  now :-(

* Wed May 14 2014 David Tardon <dtardon@redhat.com> - 1:4.0.4.2-12
- Resolves: rhbz#1097646 libreoffice crashes with multiple UNO connections

* Wed May 07 2014 David Tardon <dtardon@redhat.com> - 1:4.0.4.2-11
- Related: rhbz#1035298 require new Google C* fonts for MS Office
  compatibility

* Tue Apr 15 2014 David Tardon <dtardon@redhat.com> - 1:4.0.4.2-10
- Resolves: rhbz#1012379 sound file included in presentation displayed
  as a gray sqaure
- Resolves: rhbz#1012390 CRITICAL **: AtkObject* atk_object_wrapper_ref
- Resolves: rhbz#1038189 libreoffice does not recognize new printer
- Resolves: rhbz#1085420 LO incorrectly provides liblcms2.so.2
- Resolves: rhbz#1065629 RTF import probable regression with non-english
  BigMachines exports
- Resolves: rhbz#1020712 No Default Font showing when write in text
  boxes at first, behaving unusual
- Resolves: rhbz#1021915 Menu drop-down list overlapping with other menu
  items
- Resolves: rhbz#1035298 Transaction check errors due to file conflicts
- Related: rhbz#1035298 provide non-arch variants of openoffice.org
  provides too

* Tue Oct 08 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-9
- Resolves: rhbz#1016022 fix cut from impress and paste to writer

* Mon Oct 07 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-8
- Resolves: rhbz#1001768: fix various a11y deadlocks and crashes

* Fri Jul 26 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-7
- Resolves: rhbz#988737 no java 1:1.6 on non x86|x86_64 rhel-6

* Fri Jul 19 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-6
- Related: rhbz#919230 bump n-v-r

* Thu Jul 18 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-5
- Related: rhbz#919230 avoid signed int overflow

* Fri Jul 12 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-4
- Resolves: rhbz#983977 no bluez-libs-devel on RHEL-6

* Wed Jul 10 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-3
- Resolves: rhbz#833512 provide a /usr/bin/openoffice.org-1.9 for backwards compat
- Resolves: rhbz#902694 inaccessibile CJK/Indic shortcuts

* Mon Jul 08 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-2
- Related: rhbz#919230 merge required patches

* Wed Jul 03 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.4.2-1
- Related: rhbz#919230 bump to 4.0.4

* Tue Jul 02 2013 Caolán McNamara <caolanm@redhat.com> - 1:4.0.3.3-3
- Related: rhbz#919230 merge to last 4.0.3 F19 series

* Tue May 14 2013 Stephan Bergmann <sbergman@redhat.com> - 3.4.5.2-18
- Resolves: rhbz#820554 Java functionality broken with gcj
- Resolves: rhbz#855972 crash on switching to outline view
- Resolves: rhbz#863052 ZipIOException in MSOffice 2010 msxml
- Resolves: rhbz#902694 inaccessibile CJK/Indic shortcuts
- Resolves: rhbz#833512 missing some backwards compat launchers
- Resolves: rhbz#876742 manipulation with larger tables in impress is very slow
- Resolves: rhbz#841812 accept empty string as scalar numeric 0
- Resolves: rhbz#847519 do not access vector elements beyond size
- Resolves: rhbz#865058 retard overflow of internal table of number formats
- Resolves: rhbz#871462 remove testdocs that trigger anti-virus software

* Fri Jul 20 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-17
- Resolves: rhbz#839868 CVE-2012-2665

* Thu May 24 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-16
- Resolves: rhbz#822970 CVE-2012-2334

* Thu May 17 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-15
- Resolves: rhbz#822970 CVE-2012-1149

* Mon Apr 23 2012 David Tardon <dtardon@redhat.com> - 3.4.5.2-14
- Resolves: rhbz#815216 Unlocalized strings in print dialog of Calc

* Wed Apr 18 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-13
- Resolves: rhbz#809466 libreoffice-core (unintentionally) provides
  libraptor.so.1()() and librdf.so.0()()

* Thu Apr 12 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-12
- Resolves: rhbz#810267 better CSV import default separators
- Resolves: rhbz#807392 focus problems and tearable menus

* Tue Mar 27 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-10
- Resolves: rhbz#807243 require correct version of hsqldb

* Fri Mar 23 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-9
- Resolves: rhbz#806074 obsolete openoffice.org-debuginfo

* Tue Mar 06 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-8
- Resolves: rhbz#798983 Kannada langpack missing
- Resolves: rhbz#798926 fix endianess assumptions of lotuswordpro filter
- Resolves: rhbz#800272 complain about unknown commandline options

* Wed Feb 29 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-7
- Resolves: rhbz#788045 swriter --help wouldn't display help

* Thu Feb 09 2012 Caolán McNamara <caolanm@redhat.com> - 3.4.5.2-5
- Resolves: rhbz#747431 include 3.4.X in RHEL-6
